using TraceMap.Core;

namespace TraceMap.Tests;

// Issue #736 spec task 8: the synthetic validation matrix on top of the
// extraction slice. Covers generated/designer-source handling, protected-input
// mutation during the live capture->extract->verify scan sequence, public
// artifact privacy, repeated-scan determinism, honest reduced coverage with
// sanitized gaps, and the per-file semantic/syntax-fallback boundary.
public sealed class VisualBasicValidationMatrixTests
{
    // ---------- Generated and designer sources ----------

    [Fact]
    public void Designer_and_generated_vb_files_are_never_analyzed_or_fallback_scanned()
    {
        using var temp = new TempDirectory();
        var repo = Path.Combine(temp.Path, "repo");
        Directory.CreateDirectory(repo);
        File.WriteAllText(Path.Combine(repo, "Widget.vbproj"), """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <RootNamespace>Widget</RootNamespace>
              </PropertyGroup>
            </Project>
            """);
        // The .g/.designer/header-generated files stay inside the default SDK
        // compilation glob (they must remain protected compilation inputs), but
        // neither semantic analysis nor syntax fallback may emit evidence for
        // them.
        File.WriteAllText(Path.Combine(repo, "Live.vb"), """
            Namespace Widget
                Public Class Live
                    Public Function Name() As String
                        Return "unused"
                    End Function
                End Class
            End Namespace
            """);
        File.WriteAllText(Path.Combine(repo, "Live.designer.vb"), """
            Namespace Widget
                Partial Public Class Live
                    Private components As System.ComponentModel.IContainer
                End Class
            End Namespace
            """);
        File.WriteAllText(Path.Combine(repo, "Tooling.g.vb"), """
            Namespace Widget
                Public Class ToolingGenerated
                End Class
            End Namespace
            """);
        File.WriteAllText(Path.Combine(repo, "AssemblyInfo.vb"), """
            Namespace Widget
                Public Class AssemblyInfoShouldBeSkipped
                End Class
            End Namespace
            """);
        File.WriteAllText(Path.Combine(repo, "HeaderGenerated.vb"), """
            ' <auto-generated>
            ' Code generated by a tool; changes may be lost.
            ' </auto-generated>
            Namespace Widget
                Public Class HeaderGenerated
                End Class
            End Namespace
            """);
        Commit(repo);

        var result = ScanEngine.Scan(new ScanOptions(repo, Path.Combine(temp.Path, "out")));

        // The ordinary file is compiler-resolved exactly once. The designer and
        // SDK-generated files are skipped by the documented filename-convention
        // boundary; the auto-generated-header file keeps compiler-resolved
        // analysis like its C# counterpart (its header only gates the syntax
        // fallback, which it never reaches here).
        Assert.Contains(result.Facts, fact =>
            fact.FactType == FactTypes.TypeDeclared
            && fact.RuleId == RuleIds.VisualBasicSemanticDeclarations
            && fact.Evidence.FilePath == "Live.vb");
        Assert.Contains(result.Facts, fact =>
            fact.FactType == FactTypes.TypeDeclared
            && fact.RuleId == RuleIds.VisualBasicSemanticDeclarations
            && fact.Evidence.FilePath == "HeaderGenerated.vb");
        foreach (var generatedPath in new[] { "Live.designer.vb", "Tooling.g.vb", "AssemblyInfo.vb" })
        {
            Assert.DoesNotContain(result.Facts, fact =>
                fact.Evidence.FilePath == generatedPath
                && (fact.RuleId.StartsWith("vb.semantic.", StringComparison.Ordinal)
                    || fact.RuleId.StartsWith("vb.syntax.", StringComparison.Ordinal)));
        }

        // A generated-shape file is still a protected semantic input: mutating
        // it after snapshot capture must fail verification loudly even though
        // it never contributes evidence.
        var inventory = FileInventory.Collect(repo);
        var baseline = ScanEngine.CaptureSemanticInputSnapshot(repo, inventory);
        foreach (var generatedPath in new[] { "Live.designer.vb", "Tooling.g.vb", "HeaderGenerated.vb" })
        {
            Assert.Contains(generatedPath, baseline.Keys);
        }

        File.WriteAllText(Path.Combine(repo, "Live.designer.vb"), """
            Namespace Widget
                Partial Public Class Live
                    Private mutated As Boolean
                End Class
            End Namespace
            """);
        var semanticResult = new SemanticExtractionResult(
            [],
            [],
            true,
            false,
            new HashSet<string>(StringComparer.Ordinal),
            CompilationInputFiles: new HashSet<string>(StringComparer.Ordinal) { "Live.designer.vb" });
        Assert.Throws<SourceSnapshotException>(() =>
            ScanEngine.VerifySemanticInputSnapshot(repo, inventory, semanticResult, baseline));
    }

    // ---------- Source mutation during a live scan ----------

    [Fact]
    public void Vb_source_mutated_during_the_scan_sequence_fails_with_the_typed_snapshot_error()
    {
        using var temp = new TempDirectory();
        var repo = Path.Combine(temp.Path, "repo");
        Directory.CreateDirectory(repo);
        File.WriteAllText(Path.Combine(repo, "Mutated.vbproj"), """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <RootNamespace>Mutated</RootNamespace>
              </PropertyGroup>
            </Project>
            """);
        const string sourceRelativePath = "Live.vb";
        File.WriteAllText(Path.Combine(repo, sourceRelativePath), """
            Namespace Mutated
                Public Class Live
                    Public Sub Go()
                    End Sub
                End Class
            End Namespace
            """);
        Commit(repo);

        // This mirrors the production ScanEngine sequence: capture the
        // semantic-input snapshot, run Visual Basic semantic extraction over
        // the sources, then verify the snapshot before any fact is published.
        var inventory = FileInventory.Collect(repo);
        var baseline = ScanEngine.CaptureSemanticInputSnapshot(repo, inventory);
        var extraction = VisualBasicSemanticExtractor.Extract(
            repo,
            inventory,
            new ScanOptions(repo, Path.Combine(temp.Path, "out")));
        Assert.NotNull(extraction.AnalyzedFiles);
        Assert.Contains(sourceRelativePath, extraction.AnalyzedFiles!);

        // The mutation happens after extraction observed the source, inside
        // the protected window before publication.
        File.WriteAllText(Path.Combine(repo, sourceRelativePath), """
            Namespace Mutated
                Public Class Live
                    Public Sub Gone()
                    End Sub
                End Class
            End Namespace
            """);

        Assert.Throws<SourceSnapshotException>(() =>
            ScanEngine.VerifySemanticInputSnapshot(repo, inventory, extraction, baseline));
    }

    // ---------- Per-file semantic/syntax-fallback boundary ----------

    [Fact]
    public void Fallback_boundary_is_per_file_not_per_scan()
    {
        using var temp = new TempDirectory();
        var repo = Path.Combine(temp.Path, "repo");
        Directory.CreateDirectory(repo);
        File.WriteAllText(Path.Combine(repo, "Clean.vbproj"), """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <RootNamespace>Clean</RootNamespace>
              </PropertyGroup>
              <ItemGroup>
                <Compile Remove="Orphan.vb" />
              </ItemGroup>
            </Project>
            """);
        File.WriteAllText(Path.Combine(repo, "Compiled.vb"), """
            Namespace Clean
                Public Class Compiled
                    Public Sub Go()
                    End Sub
                End Class
            End Namespace
            """);
        // Not included in the project: reachable only through per-file fallback.
        File.WriteAllText(Path.Combine(repo, "Orphan.vb"), """
            Namespace Orphan
                Public Class Orphaned
                    Public Function Build() As String
                        Dim made As New Orphaned()
                        Return made.ToString()
                    End Function
                End Class
            End Namespace
            """);
        Commit(repo);

        var result = ScanEngine.Scan(new ScanOptions(repo, Path.Combine(temp.Path, "out")));

        // The compiled file keeps Tier1-only coverage.
        Assert.Contains(result.Facts, fact =>
            fact.FactType == FactTypes.TypeDeclared
            && fact.RuleId == RuleIds.VisualBasicSemanticDeclarations
            && fact.Evidence.FilePath == "Compiled.vb");
        Assert.DoesNotContain(result.Facts, fact =>
            fact.Evidence.FilePath == "Compiled.vb"
            && fact.RuleId.StartsWith("vb.syntax.", StringComparison.Ordinal));
        Assert.DoesNotContain(result.Facts, fact =>
            fact.FactType == FactTypes.AnalysisGap
            && fact.Evidence.FilePath == "Compiled.vb"
            && fact.Properties.GetValueOrDefault("gapKind") == "SemanticAnalysisUnavailable");

        // The orphan file keeps Tier3-only coverage with its explicit gap.
        Assert.Contains(result.Facts, fact =>
            fact.FactType == FactTypes.TypeDeclared
            && fact.RuleId == RuleIds.VisualBasicSyntaxDeclarations
            && fact.EvidenceTier == EvidenceTiers.Tier3SyntaxOrTextual
            && fact.Evidence.FilePath == "Orphan.vb");
        var unavailableGap = Assert.Single(result.Facts, fact =>
            fact.FactType == FactTypes.AnalysisGap
            && fact.Properties.GetValueOrDefault("gapKind") == "SemanticAnalysisUnavailable");
        Assert.Equal("Orphan.vb", unavailableGap.Evidence.FilePath);
    }

    // ---------- Reduced coverage honesty and sanitized gaps ----------

    [Fact]
    public void Reduced_vb_scan_reports_sanitized_gaps_with_safe_diagnostic_ids()
    {
        var repoRoot = FindRepoRoot();
        var result = ScanEngine.Scan(new ScanOptions(
            Path.Combine(repoRoot, "samples", "vb-legacy-sample"),
            Path.Combine(Path.GetTempPath(), "tracemap-vb-matrix-reduced")));

        Assert.Equal("FailedOrPartial", result.Manifest.BuildStatus);
        Assert.EndsWith("Reduced", result.Manifest.AnalysisLevel, StringComparison.Ordinal);

        var workspaceGaps = result.Facts
            .Where(fact => fact.FactType == FactTypes.AnalysisGap
                && fact.RuleId == RuleIds.VisualBasicSemanticWorkspace)
            .ToArray();
        Assert.NotEmpty(workspaceGaps);

        // Every gap message is the stable category text: no source-derived
        // text, no file paths, no raw compiler message content.
        foreach (var gap in workspaceGaps)
        {
            var message = gap.Properties["message"];
            if (gap.Properties.GetValueOrDefault("gapKind") is "CompilationDiagnostic" or "WorkspaceDiagnostic")
            {
                Assert.True(
                    message.StartsWith("Compiler diagnostic category: ", StringComparison.Ordinal)
                    || message.StartsWith("Workspace diagnostic category: ", StringComparison.Ordinal),
                    $"Unexpected unsanitized gap message: {message}");
            }

            Assert.DoesNotContain('/', message);
            Assert.DoesNotContain('\\', message);
            Assert.DoesNotContain(".vb", message, StringComparison.Ordinal);
            Assert.Equal("category-only", gap.Properties["sanitization"]);
            Assert.True(gap.Properties["messageHash"].Length > 0);
        }

        // Compiler-diagnostic gaps carry the bounded Visual Basic diagnostic
        // id (BCxxxxx), never the raw message.
        var compilationGaps = workspaceGaps
            .Where(fact => fact.Properties.GetValueOrDefault("gapKind") == "CompilationDiagnostic")
            .ToArray();
        Assert.NotEmpty(compilationGaps);
        Assert.All(compilationGaps, gap =>
            Assert.Matches(@"^BC[0-9]{5}$", gap.Properties["diagnosticId"]));

        // The legacy fixture is only partially bound: its readable files keep
        // partial Tier1 evidence and must not receive Tier3 duplicates.
        var tier1Files = result.Facts
            .Where(fact => fact.EvidenceTier == EvidenceTiers.Tier1Semantic)
            .Select(fact => fact.Evidence.FilePath)
            .Distinct(StringComparer.Ordinal)
            .ToHashSet(StringComparer.Ordinal);
        Assert.Superset(
            tier1Files,
            new HashSet<string>(StringComparer.Ordinal) { "CatalogModels.vb", "CatalogService.vb", "LegacyQueueBridge.vb" });
        Assert.DoesNotContain(result.Facts, fact =>
            fact.RuleId == RuleIds.VisualBasicSyntaxDeclarations
            || fact.RuleId == RuleIds.VisualBasicSyntaxMemberAccess
            || fact.RuleId == RuleIds.VisualBasicSyntaxObjectCreation);
        Assert.DoesNotContain(result.Facts, fact =>
            fact.FactType == FactTypes.AnalysisGap
            && fact.Properties.GetValueOrDefault("gapKind") == "SemanticAnalysisUnavailable"
            && tier1Files.Contains(fact.Evidence.FilePath));
    }

    // ---------- Deterministic repeated scans ----------

    [Fact]
    public async Task Repeated_cli_scans_produce_byte_identical_facts()
    {
        var repoRoot = FindRepoRoot();
        using var temp = new TempDirectory();
        var first = Path.Combine(temp.Path, "one");
        var second = Path.Combine(temp.Path, "two");
        using var output = new StringWriter();
        using var error = new StringWriter();

        Assert.Equal(0, await TraceMap.Cli.TraceMapCommand.RunAsync(
            ["scan", "--repo", Path.Combine(repoRoot, "samples", "vb-modern-sample"), "--out", first], output, error));
        Assert.Equal(0, await TraceMap.Cli.TraceMapCommand.RunAsync(
            ["scan", "--repo", Path.Combine(repoRoot, "samples", "vb-modern-sample"), "--out", second], output, error));

        Assert.Equal(
            await File.ReadAllBytesAsync(Path.Combine(first, "facts.ndjson")),
            await File.ReadAllBytesAsync(Path.Combine(second, "facts.ndjson")));
    }

    // ---------- Public artifact privacy ----------

    [Fact]
    public async Task Vb_scan_artifacts_stay_public_safe()
    {
        using var temp = new TempDirectory();
        var repo = Path.Combine(temp.Path, "repo");
        Directory.CreateDirectory(repo);
        File.WriteAllText(Path.Combine(repo, "Secrets.vbproj"), """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <RootNamespace>Secrets</RootNamespace>
              </PropertyGroup>
            </Project>
            """);
        File.WriteAllText(Path.Combine(repo, "Secrets.vb"), """
            Module Secrets
                Const AccessToken As String = "vb-private-value-sentinel"
                Sub Main()
                    System.Console.WriteLine(AccessToken)
                    Dim deferred = Sub() System.Console.WriteLine(AccessToken)
                    deferred()
                End Sub
            End Module
            """);
        // A parse-broken file whose unique identifier would leak through raw
        // compiler diagnostic text if messages were not sanitized.
        File.WriteAllText(Path.Combine(repo, "Broken.vb"), """
            Module Broken
                Sub DefinitelyBroken() UniqueSyntaxMarkerName
            End Module
            """);
        Commit(repo);

        var outputPath = Path.Combine(temp.Path, "out");
        using var output = new StringWriter();
        using var error = new StringWriter();
        Assert.Equal(0, await TraceMap.Cli.TraceMapCommand.RunAsync(
            ["scan", "--repo", repo, "--out", outputPath], output, error));

        foreach (var artifact in new[]
                 {
                     Path.Combine(outputPath, "scan-manifest.json"),
                     Path.Combine(outputPath, "facts.ndjson"),
                     Path.Combine(outputPath, "report.md"),
                     Path.Combine(outputPath, "logs", "analyzer.log")
                 })
        {
            var content = await File.ReadAllTextAsync(artifact);
            Assert.DoesNotContain(temp.Path, content, StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain("vb-private-value-sentinel", content, StringComparison.Ordinal);
            Assert.DoesNotContain("UniqueSyntaxMarkerName", content, StringComparison.Ordinal);
        }
    }

    // ---------- Symbol identity stability ----------

    [Fact]
    public void Vb_symbol_identities_are_stable_across_fact_families_and_constructs()
    {
        using var temp = new TempDirectory();
        var repo = Path.Combine(temp.Path, "repo");
        Directory.CreateDirectory(repo);
        File.WriteAllText(Path.Combine(repo, "Identity.vbproj"), """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <RootNamespace>Identity</RootNamespace>
              </PropertyGroup>
            </Project>
            """);
        File.WriteAllText(Path.Combine(repo, "Shapes.vb"), """
            Namespace Identity
                Public Interface IMemberSource
                    Function Fetch(id As Integer) As String
                End Interface

                Public Module GlobalCounters
                    Public Property Total As Integer = 0
                    Public Sub Bump(amount As Integer)
                        Total += amount
                    End Sub
                End Module

                Public Class Registry
                    Private ReadOnly _entries As New Dictionary(Of Integer, String)()
                    Public Sub New()
                        _entries(0) = "empty"
                    End Sub
                    Public Sub New(seed As Integer)
                        Me.New()
                    End Sub
                    Public Default ReadOnly Property Item(index As Integer) As String
                        Get
                            Return _entries(index)
                        End Get
                    End Property
                    Public Overridable Function Describe() As String
                        Return "registry"
                    End Function
                End Class

                Public Class AuditedRegistry
                    Inherits Registry
                    Implements IMemberSource
                    Public Overrides Function Describe() As String
                        Return "audited"
                    End Function
                    Public Function Fetch(id As Integer) As String Implements IMemberSource.Fetch
                        Dim mirror As New Registry()
                        Dim other As New Registry(7)
                        GlobalCounters.Bump(amount:=1)
                        Return Me(id) & mirror.Describe() & other.Describe()
                    End Function
                    Public Sub Copy(target As String, ParamArray tags As String())
                    End Sub
                End Class
            End Namespace
            """);
        Commit(repo);

        var result = ScanEngine.Scan(new ScanOptions(repo, Path.Combine(temp.Path, "out")));
        var semanticFacts = result.Facts
            .Where(fact => fact.RuleId.StartsWith("vb.semantic.", StringComparison.Ordinal))
            .ToArray();

        string PropertyOf(CodeFact fact, string key) => fact.Properties.TryGetValue(key, out var value) ? value : string.Empty;
        string IdOf(CodeFact fact, string prefix) => PropertyOf(fact, $"{prefix}SymbolId");

        // Module member: declared once, invoked through the module-qualified
        // name, and both fact families resolve the same method identity.
        var bumpDeclared = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.MethodDeclared
            && fact.ContractElement == "Bump");
        var bumpInvoked = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.MethodInvoked
            && fact.ContractElement == "Bump");
        Assert.Equal(IdOf(bumpDeclared, "target"), IdOf(bumpInvoked, "target"));
        Assert.Contains("GlobalCounters", IdOf(bumpDeclared, "target"), StringComparison.Ordinal);

        // Named argument binds to the resolved parameter identity.
        var bumpArgument = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.ArgumentPassed
            && fact.ContractElement == "amount");
        Assert.Equal("0", PropertyOf(bumpArgument, "parameterOrdinal"));
        Assert.Equal("Literal", PropertyOf(bumpArgument, "argumentExpressionKind"));

        // Default property: the indexed access Me(id) resolves to the same
        // identity as the Item declaration. Dictionary indexer accesses in the
        // same file are distinct identities and are not confused with it.
        var itemDeclared = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.PropertyDeclared
            && fact.ContractElement == "Item"
            && PropertyOf(fact, "isDefault") == "True"
            && fact.TargetSymbol!.Contains("Registry.Item", StringComparison.Ordinal));
        var itemAccessed = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.PropertyAccessed
            && fact.ContractElement == "Item"
            && PropertyOf(fact, "isDefault") == "True"
            && fact.TargetSymbol!.Contains("Registry.Item", StringComparison.Ordinal));
        Assert.Equal(IdOf(itemDeclared, "target"), IdOf(itemAccessed, "target"));

        // Constructor identities use the .ctor metadata name and the object
        // creation and its constructor call edge agree on that identity.
        var creations = semanticFacts
            .Where(fact => fact.FactType == FactTypes.ObjectCreated
                && PropertyOf(fact, "createdTypeName") == "Registry")
            .ToArray();
        Assert.Equal(2, creations.Length);
        Assert.All(creations, creation =>
            Assert.Contains(".ctor", PropertyOf(creation, "constructorSymbolId"), StringComparison.Ordinal));
        var creationCallEdges = semanticFacts
            .Where(fact => fact.FactType == FactTypes.CallEdge
                && PropertyOf(fact, "callKind") == "SemanticObjectCreation"
                && PropertyOf(fact, "calleeName") == "Registry")
            .ToArray();
        Assert.Equal(2, creationCallEdges.Length);
        Assert.Equal(
            creations.Select(creation => PropertyOf(creation, "constructorSymbolId")).OrderBy(value => value).ToArray(),
            creationCallEdges.Select(edge => IdOf(edge, "target")).OrderBy(value => value).ToArray());

        // Override relationship: the overriding method's declared identity is
        // the relationship source; the base method's declared identity is the
        // relationship target.
        var describeOverride = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.SymbolRelationship
            && PropertyOf(fact, "relationshipKind") == "Overrides"
            && PropertyOf(fact, "sourceSymbolKind") == "Method");
        var auditedDescribe = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.MethodDeclared
            && PropertyOf(fact, "containingType").EndsWith("AuditedRegistry", StringComparison.Ordinal)
            && fact.ContractElement == "Describe");
        var baseDescribe = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.MethodDeclared
            && PropertyOf(fact, "containingType").EndsWith("Registry", StringComparison.Ordinal)
            && fact.ContractElement == "Describe"
            && PropertyOf(fact, "containingType").Contains("Audited", StringComparison.Ordinal) == false);
        Assert.Equal(IdOf(auditedDescribe, "target"), IdOf(describeOverride, "source"));
        Assert.Equal(IdOf(baseDescribe, "target"), IdOf(describeOverride, "target"));

        // Interface member implementation: the relationship target identity is
        // the declared interface method's identity.
        var fetchImplementation = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.SymbolRelationship
            && PropertyOf(fact, "relationshipKind") == "ImplementsInterfaceMember");
        var interfaceFetch = Assert.Single(semanticFacts, fact =>
            fact.FactType == FactTypes.MethodDeclared
            && PropertyOf(fact, "containingType").EndsWith("IMemberSource", StringComparison.Ordinal)
            && fact.ContractElement == "Fetch");
        Assert.Equal(IdOf(interfaceFetch, "target"), IdOf(fetchImplementation, "target"));

        // ByRef/ParamArray parameters keep one stable declared identity per
        // parameter, and no fact family mints a second one.
        var declaredParameterIds = semanticFacts
            .Where(fact => fact.FactType == FactTypes.ParameterDeclared)
            .Select(fact => IdOf(fact, "target"))
            .ToArray();
        Assert.All(semanticFacts.Where(fact => PropertyOf(fact, "parameterSymbolId").Length > 0), fact =>
            Assert.Contains(PropertyOf(fact, "parameterSymbolId"), declaredParameterIds));
    }

    [Fact]
    public void Vb_lambda_call_sites_keep_scans_running_and_bounded_caller_text()
    {
        using var temp = new TempDirectory();
        var repo = Path.Combine(temp.Path, "repo");
        Directory.CreateDirectory(repo);
        File.WriteAllText(Path.Combine(repo, "Deferred.vbproj"), """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <RootNamespace>Deferred</RootNamespace>
              </PropertyGroup>
            </Project>
            """);
        File.WriteAllText(Path.Combine(repo, "Deferred.vb"), """
            Namespace Deferred
                Public Class Runner
                    Public Sub Run()
                        Dim deferred = Sub() System.Console.WriteLine("unused")
                        deferred()
                    End Sub
                End Class
            End Namespace
            """);
        Commit(repo);

        // Regression: VB anonymous-method caller display text must not break
        // shared downstream fact indexing (it previously crashed the WebForms
        // direct-evidence index on symbol text shaped "()").
        var result = ScanEngine.Scan(new ScanOptions(repo, Path.Combine(temp.Path, "out")));

        var lambdaCall = Assert.Single(result.Facts, fact =>
            fact.FactType == FactTypes.MethodInvoked
            && fact.ContractElement == "WriteLine"
            && fact.Evidence.FilePath == "Deferred.vb");
        Assert.Equal(EvidenceTiers.Tier1Semantic, lambdaCall.EvidenceTier);
        // The caller text is the anonymous-method display; it must stay
        // bounded and must never be mistaken for a resolvable member name.
        Assert.False(string.IsNullOrWhiteSpace(lambdaCall.SourceSymbol));
        Assert.True(lambdaCall.SourceSymbol!.Length <= 256);
    }

    // ---------- Helpers ----------

    private static void Commit(string repo, string message = "vb validation matrix fixture")
    {
        RunGit(repo, "init");
        RunGit(repo, "add", "-A");
        RunGit(repo, "-c", "user.name=TraceMap", "-c", "user.email=tests@example.invalid", "commit", "-m", message, "--allow-empty");
    }

    private static void RunGit(string repo, params string[] arguments)
    {
        using var process = new System.Diagnostics.Process
        {
            StartInfo = new System.Diagnostics.ProcessStartInfo
            {
                FileName = "git",
                WorkingDirectory = repo,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false
            }
        };
        foreach (var argument in arguments)
        {
            process.StartInfo.ArgumentList.Add(argument);
        }

        process.Start();
        process.WaitForExit(30_000);
        Assert.Equal(0, process.ExitCode);
    }

    private static string FindRepoRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (Directory.Exists(Path.Combine(directory.FullName, ".git"))
                && Directory.Exists(Path.Combine(directory.FullName, "samples")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("Repository root not found.");
    }
}
