from __future__ import annotations

import json
import subprocess
from pathlib import Path

from tracemap_py.engine import make_options, scan
from tracemap_py.lockfiles import read_lockfiles
from tracemap_py.models import ScanManifest

UV_LOCK = """\
version = 1
requires-python = ">=3.11"

[[package]]
name = "fixture-python-app"
version = "0.1.0"
source = { virtual = "." }
dependencies = [
    { name = "requests" },
    { name = "flask" },
]

[package.metadata]
requires-dist = [
    { name = "flask", specifier = "==3.0.3" },
    { name = "requests", specifier = ">=2.31.0" },
]

[[package]]
name = "requests"
version = "2.32.3"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "urllib3" },
]
sdist = { url = "https://files.pythonhosted.org/packages/source/r/requests/requests-2.32.3.tar.gz", hash = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", size = 131000 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/py3/r/requests/requests-2.32.3-py3-none-any.whl", hash = "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", size = 62000 },
    { url = "https://files.pythonhosted.org/packages/py3/r/requests/requests-2.32.3-py3-none-win_amd64.whl", hash = "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", size = 64000 },
]

[[package]]
name = "urllib3"
version = "2.2.2"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/packages/source/u/urllib3/urllib3-2.2.2.tar.gz", hash = "sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd", size = 290000 }

[[package]]
name = "flask"
version = "3.0.3"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/packages/source/f/flask/flask-3.0.3.tar.gz", hash = "sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", size = 208000 }
"""

POETRY_LOCK = """\
# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.
version = "2.0"

[[package]]
name = "requests"
version = "2.32.3"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.8"
files = [
    {file = "requests-2.32.3-py3-none-any.whl", hash = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},
    {file = "requests-2.32.3.tar.gz", hash = "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"},
]

[package.dependencies]
urllib3 = ">=1.21.1"

[[package]]
name = "urllib3"
version = "2.2.2"
description = "HTTP library with thread-safe connection pooling."
optional = false
python-versions = ">=3.8"
files = [
    {file = "urllib3-2.2.2.tar.gz", hash = "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"},
]

[metadata]
lock-version = "2.0"
python-versions = ">=3.8"
content-hash = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
"""

PYPROJECT = """\
[project]
name = "fixture-python-app"
version = "0.1.0"
dependencies = [
    "requests>=2.31.0",
    "flask==3.0.3",
]
"""


def _manifest(scan_id: str) -> ScanManifest:
    return ScanManifest(scan_id, "repo", None, "main", "0" * 40, "python-adapter/0.1.0", "2026-06-13T00:00:00+00:00", "Level1SemanticAnalysisReduced", "FailedOrPartial", [], [], ["python"], [])


def _package_facts(facts):
    return [fact for fact in facts if fact.fact_type == "PackageReferenced"]


def _gap_facts(facts):
    return [fact for fact in facts if fact.fact_type == "AnalysisGap"]


def _by_name(facts, name):
    return [fact for fact in _package_facts(facts) if fact.properties["packageName"] == name]


def test_uv_lock_emits_resolved_versions_with_proven_direct_and_transitive(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(UV_LOCK, encoding="utf-8")
    gaps: list[str] = []

    facts = read_lockfiles(tmp_path, _manifest("uv"), [lock], [], gaps)

    packages = _package_facts(facts)
    assert {fact.properties["packageName"] for fact in packages} == {"requests", "urllib3", "flask"}
    requests = _by_name(facts, "requests")[0]
    assert requests.properties["resolvedVersion"] == "2.32.3"
    assert requests.properties["version"] == "2.32.3"
    assert requests.properties["ecosystem"] == "python"
    assert requests.properties["sourceKind"] == "lockfile"
    assert requests.properties["manifestKind"] == "uv.lock"
    assert requests.properties["packageManager"] == "uv"
    assert requests.properties["lockfilePath"] == "uv.lock"
    assert len(requests.properties["lockfileHash"]) == 32
    assert requests.properties["registryOrigin"] == "pypi.org"
    assert requests.properties["dependencyRelation"] == "direct"
    assert _by_name(facts, "urllib3")[0].properties["dependencyRelation"] == "transitive"
    assert requests.evidence.extractor_id == "PythonLockfileExtractor"
    assert requests.evidence.extractor_version == "python-lockfile/0.1.0"
    assert requests.evidence.file_path == "uv.lock"
    assert requests.evidence.start_line == 19  # the [[package]] header line of the requests entry
    assert gaps == []


def test_uv_and_poetry_lockfile_hashes_are_never_artifact_digests(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(UV_LOCK, encoding="utf-8")

    facts = read_lockfiles(tmp_path, _manifest("uv-digest"), [lock], [], [])

    for fact in _package_facts(facts):
        assert "artifactDigest" not in fact.properties
        assert "artifactDigestAlgorithm" not in fact.properties
    gap_kinds = {fact.properties["gapKind"] for fact in _gap_facts(facts)}
    assert "LockfileDigestUnavailable" in gap_kinds


def test_uv_lock_without_root_entry_emits_relation_capability_gap(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(
        'version = 1\n\n[[package]]\nname = "requests"\nversion = "2.32.3"\nsource = { registry = "https://pypi.org/simple" }\n',
        encoding="utf-8",
    )

    facts = read_lockfiles(tmp_path, _manifest("uv-no-root"), [lock], [], [])

    requests = _by_name(facts, "requests")[0]
    assert "dependencyRelation" not in requests.properties
    gap_kinds = {fact.properties["gapKind"] for fact in _gap_facts(facts)}
    assert "DirectTransitiveUnavailable" in gap_kinds


def test_uv_root_with_malformed_dependency_shape_does_not_prove_relations(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(
        "version = 1\n"
        '\n[[package]]\nname = "fixture"\nversion = "0.1.0"\nsource = { virtual = "." }\ndependencies = "requests"\n'
        '\n[[package]]\nname = "requests"\nversion = "2.32.3"\nsource = { registry = "https://pypi.org/simple" }\n',
        encoding="utf-8",
    )

    facts = read_lockfiles(tmp_path, _manifest("uv-malformed-root"), [lock], [], [])

    requests = _by_name(facts, "requests")[0]
    assert "dependencyRelation" not in requests.properties
    assert "DirectTransitiveUnavailable" in {fact.properties["gapKind"] for fact in _gap_facts(facts)}


def test_uv_lock_non_registry_sources_emit_explicit_gaps(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(
        "version = 1\n"
        '\n[[package]]\nname = "evil-git-dep"\nversion = "1.0.0"\nsource = { git = "https://example.invalid/pkg?rev=abc" }\n'
        '\n[[package]]\nname = "local-path-dep"\nversion = "0.0.0"\nsource = { path = "vendor/local" }\n',
        encoding="utf-8",
    )

    facts = read_lockfiles(tmp_path, _manifest("uv-git"), [lock], [], [])

    assert _package_facts(facts) == []
    source_gaps = [fact for fact in _gap_facts(facts) if fact.properties["gapKind"] == "python-lock-entry-source-unsupported"]
    assert len(source_gaps) == 2


def test_uv_editable_dependency_is_not_silently_treated_as_the_project_root(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(
        "version = 1\n"
        '\n[[package]]\nname = "fixture"\nversion = "0.1.0"\nsource = { editable = "." }\ndependencies = [{ name = "shared-lib" }, { name = "requests" }]\n'
        '\n[[package]]\nname = "shared-lib"\nversion = "0.2.0"\nsource = { editable = "../shared-lib" }\n'
        '\n[[package]]\nname = "requests"\nversion = "2.32.3"\nsource = { registry = "https://pypi.org/simple" }\n',
        encoding="utf-8",
    )

    facts = read_lockfiles(tmp_path, _manifest("uv-editable-dependency"), [lock], [], [])

    assert {fact.properties["packageName"] for fact in _package_facts(facts)} == {"requests"}
    assert _by_name(facts, "requests")[0].properties["dependencyRelation"] == "direct"
    source_gaps = [fact for fact in _gap_facts(facts) if fact.properties["gapKind"] == "python-lock-entry-source-unsupported"]
    assert len(source_gaps) == 1


def test_uv_skips_only_declared_non_excluded_workspace_entries(tmp_path: Path) -> None:
    root_manifest = tmp_path / "pyproject.toml"
    member_manifest = tmp_path / "packages" / "member" / "pyproject.toml"
    excluded_manifest = tmp_path / "packages" / "excluded" / "pyproject.toml"
    member_manifest.parent.mkdir(parents=True)
    excluded_manifest.parent.mkdir(parents=True)
    root_manifest.write_text(
        '[project]\nname = "fixture"\n[tool.uv.workspace]\nmembers = ["packages/*"]\nexclude = ["packages/excluded"]\n',
        encoding="utf-8",
    )
    member_manifest.write_text('[project]\nname = "member"\n', encoding="utf-8")
    excluded_manifest.write_text('[project]\nname = "excluded"\n', encoding="utf-8")
    lock = tmp_path / "uv.lock"
    lock.write_text(
        "version = 1\n"
        '\n[[package]]\nname = "fixture"\nversion = "0.1.0"\nsource = { virtual = "." }\ndependencies = [{ name = "requests" }]\n'
        '\n[[package]]\nname = "member"\nversion = "0.1.0"\nsource = { editable = "packages/member" }\n'
        '\n[[package]]\nname = "excluded"\nversion = "0.1.0"\nsource = { editable = "packages/excluded" }\n'
        '\n[[package]]\nname = "requests"\nversion = "2.32.3"\nsource = { registry = "https://pypi.org/simple" }\n',
        encoding="utf-8",
    )

    facts = read_lockfiles(
        tmp_path,
        _manifest("uv-workspace"),
        [lock],
        [root_manifest, member_manifest, excluded_manifest],
        [],
    )

    assert {fact.properties["packageName"] for fact in _package_facts(facts)} == {"requests"}
    source_gaps = [fact for fact in _gap_facts(facts) if fact.properties["gapKind"] == "python-lock-entry-source-unsupported"]
    assert len(source_gaps) == 1


def test_uv_lock_unsupported_version_fails_closed(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text('version = 2\n\n[[package]]\nname = "requests"\nversion = "2.32.3"\nsource = { registry = "https://pypi.org/simple" }\n', encoding="utf-8")
    gaps: list[str] = []

    facts = read_lockfiles(tmp_path, _manifest("uv-v2"), [lock], [], gaps)

    assert _package_facts(facts) == []
    assert [fact.properties["gapKind"] for fact in _gap_facts(facts)] == ["python-lock-unsupported"]
    assert gaps and gaps[0].startswith("PythonLockUnsupported:")


def test_malformed_or_truncated_lockfile_emits_parse_gap(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text('version = 1\n\n[[package]]\nname = "requests"\nversion = "2.32.3\n', encoding="utf-8")
    gaps: list[str] = []

    facts = read_lockfiles(tmp_path, _manifest("uv-truncated"), [lock], [], gaps)

    assert _package_facts(facts) == []
    assert [fact.properties["gapKind"] for fact in _gap_facts(facts)] == ["python-lock-parse"]
    assert gaps and gaps[0].startswith("PythonLockParseFailed:")


def test_unsafe_names_and_versions_fail_closed(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(
        "version = 1\n"
        '\n[[package]]\nname = "../etc/passwd"\nversion = "1.0.0"\nsource = { registry = "https://pypi.org/simple" }\n'
        '\n[[package]]\nname = "requests"\nversion = "git+https://example.invalid/x.git#deadbeef"\nsource = { registry = "https://pypi.org/simple" }\n'
        '\n[[package]]\nname = "noversion"\nsource = { registry = "https://pypi.org/simple" }\n',
        encoding="utf-8",
    )

    facts = read_lockfiles(tmp_path, _manifest("uv-unsafe"), [lock], [], [])

    packages = _package_facts(facts)
    assert len(packages) == 1
    requests = packages[0]
    assert requests.properties["packageName"] == "requests"
    assert "resolvedVersion" not in requests.properties
    assert requests.properties["redactionReason"] == "unsafe-package-version"
    assert requests.properties["versionHash"].startswith("version-hash:")
    gap_kinds = [fact.properties["gapKind"] for fact in _gap_facts(facts)]
    assert gap_kinds.count("python-lock-entry-unsafe") == 1
    assert gap_kinds.count("python-lock-entry-resolved-missing") == 1


def test_duplicate_entries_stay_deterministic(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(
        "version = 1\n"
        '\n[[package]]\nname = "requests"\nversion = "2.32.3"\nsource = { registry = "https://pypi.org/simple" }\n'
        '\n[[package]]\nname = "requests"\nversion = "2.31.0"\nsource = { registry = "https://pypi.org/simple" }\n'
        '\n[[package]]\nname = "requests"\nversion = "2.32.3"\nsource = { registry = "https://pypi.org/simple" }\n',
        encoding="utf-8",
    )

    first = read_lockfiles(tmp_path, _manifest("uv-dup"), [lock], [], [])
    second = read_lockfiles(tmp_path, _manifest("uv-dup"), [lock], [], [])

    packages = _package_facts(first)
    assert [fact.properties["resolvedVersion"] for fact in packages] == ["2.32.3", "2.31.0", "2.32.3"]
    assert [fact.evidence.start_line for fact in packages] == [3, 8, 13]
    assert [json.dumps(fact.to_json(), sort_keys=True) for fact in first] == [json.dumps(fact.to_json(), sort_keys=True) for fact in second]


def test_multiline_string_package_headers_fall_back_to_file_anchor(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(
        "version = 1\n"
        '\n[[package]]\nname = "requests"\nversion = "2.32.3"\ndescription = """\n[[package]]\n"""\nsource = { registry = "https://pypi.org/simple" }\n',
        encoding="utf-8",
    )

    facts = read_lockfiles(tmp_path, _manifest("uv-multiline"), [lock], [], [])

    requests = _by_name(facts, "requests")[0]
    assert requests.properties["resolvedVersion"] == "2.32.3"
    assert requests.evidence.start_line == 1
    assert requests.evidence.end_line == 1


def test_poetry_lock_relations_come_from_pyproject_declarations(tmp_path: Path) -> None:
    lock = tmp_path / "poetry.lock"
    lock.write_text(POETRY_LOCK, encoding="utf-8")
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(PYPROJECT, encoding="utf-8")

    facts = read_lockfiles(tmp_path, _manifest("poetry"), [lock], [pyproject], [])

    requests = _by_name(facts, "requests")[0]
    urllib3 = _by_name(facts, "urllib3")[0]
    assert requests.properties["resolvedVersion"] == "2.32.3"
    assert requests.properties["manifestKind"] == "poetry.lock"
    assert requests.properties["packageManager"] == "poetry"
    assert requests.properties["dependencyRelation"] == "direct"
    assert urllib3.properties["dependencyRelation"] == "transitive"
    assert "registryOrigin" not in requests.properties
    gap_kinds = {fact.properties["gapKind"] for fact in _gap_facts(facts)}
    assert "LockfileDigestUnavailable" in gap_kinds
    assert "DirectTransitiveUnavailable" not in gap_kinds


def test_poetry_lock_uses_only_its_sibling_pyproject_in_monorepos(tmp_path: Path) -> None:
    app_a = tmp_path / "app-a"
    app_b = tmp_path / "app-b"
    app_a.mkdir()
    app_b.mkdir()
    lock_a = app_a / "poetry.lock"
    lock_b = app_b / "poetry.lock"
    lock_a.write_text(POETRY_LOCK, encoding="utf-8")
    lock_b.write_text(POETRY_LOCK, encoding="utf-8")
    manifest_a = app_a / "pyproject.toml"
    manifest_b = app_b / "pyproject.toml"
    manifest_a.write_text('[project]\ndependencies = ["requests"]\n', encoding="utf-8")
    manifest_b.write_text('[project]\ndependencies = ["urllib3"]\n', encoding="utf-8")

    facts = read_lockfiles(
        tmp_path,
        _manifest("poetry-monorepo"),
        [lock_a, lock_b],
        [manifest_a, manifest_b],
        [],
    )

    by_file_and_name = {
        (fact.evidence.file_path, fact.properties["packageName"]): fact.properties["dependencyRelation"]
        for fact in _package_facts(facts)
    }
    assert by_file_and_name[("app-a/poetry.lock", "requests")] == "direct"
    assert by_file_and_name[("app-a/poetry.lock", "urllib3")] == "transitive"
    assert by_file_and_name[("app-b/poetry.lock", "requests")] == "transitive"
    assert by_file_and_name[("app-b/poetry.lock", "urllib3")] == "direct"


def test_poetry_non_registry_sources_fail_closed(tmp_path: Path) -> None:
    lock = tmp_path / "poetry.lock"
    content = POETRY_LOCK.replace(
        'name = "requests"\nversion = "2.32.3"',
        'name = "requests"\nversion = "2.32.3"\nsource = { type = "git", url = "https://example.invalid/fork.git" }',
    ).replace(
        'name = "urllib3"\nversion = "2.2.2"',
        'name = "urllib3"\nversion = "2.2.2"\nsource = { type = "legacy", url = "https://packages.example.invalid/simple" }',
    )
    lock.write_text(content, encoding="utf-8")

    facts = read_lockfiles(tmp_path, _manifest("poetry-sources"), [lock], [], [])

    assert _by_name(facts, "requests") == []
    urllib3 = _by_name(facts, "urllib3")[0]
    assert urllib3.properties["registryOrigin"] == "packages.example.invalid"
    source_gaps = [fact for fact in _gap_facts(facts) if fact.properties["gapKind"] == "python-lock-entry-source-unsupported"]
    assert len(source_gaps) == 1


def test_malformed_pyproject_tables_do_not_abort_poetry_lock_extraction(tmp_path: Path) -> None:
    lock = tmp_path / "poetry.lock"
    lock.write_text(POETRY_LOCK, encoding="utf-8")
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text('project = "dynamic"\ntool = "invalid"\n', encoding="utf-8")

    facts = read_lockfiles(tmp_path, _manifest("poetry-malformed-manifest"), [lock], [pyproject], [])

    assert {fact.properties["packageName"] for fact in _package_facts(facts)} == {"requests", "urllib3"}
    assert all("dependencyRelation" not in fact.properties for fact in _package_facts(facts))
    assert "DirectTransitiveUnavailable" in {fact.properties["gapKind"] for fact in _gap_facts(facts)}


def test_poetry_lock_without_pyproject_emits_relation_capability_gap(tmp_path: Path) -> None:
    lock = tmp_path / "poetry.lock"
    lock.write_text(POETRY_LOCK, encoding="utf-8")

    facts = read_lockfiles(tmp_path, _manifest("poetry-no-pyproject"), [lock], [], [])

    for fact in _package_facts(facts):
        assert "dependencyRelation" not in fact.properties
    gap_kinds = {fact.properties["gapKind"] for fact in _gap_facts(facts)}
    assert "DirectTransitiveUnavailable" in gap_kinds


def test_poetry_lock_unsupported_lock_version_fails_closed(tmp_path: Path) -> None:
    lock = tmp_path / "poetry.lock"
    lock.write_text(POETRY_LOCK.replace('lock-version = "2.0"', 'lock-version = "9.9"'), encoding="utf-8")
    gaps: list[str] = []

    facts = read_lockfiles(tmp_path, _manifest("poetry-unsupported"), [lock], [], gaps)

    assert _package_facts(facts) == []
    assert [fact.properties["gapKind"] for fact in _gap_facts(facts)] == ["python-lock-unsupported"]
    assert gaps and gaps[0].startswith("PythonLockUnsupported:")


def test_repeated_lockfile_extraction_is_byte_identical(tmp_path: Path) -> None:
    lock = tmp_path / "uv.lock"
    lock.write_text(UV_LOCK, encoding="utf-8")
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(PYPROJECT, encoding="utf-8")
    poetry = tmp_path / "poetry.lock"
    poetry.write_text(POETRY_LOCK, encoding="utf-8")

    first = read_lockfiles(tmp_path, _manifest("repeat"), [lock, poetry], [pyproject], [])
    second = read_lockfiles(tmp_path, _manifest("repeat"), [lock, poetry], [pyproject], [])

    assert [fact.fact_id for fact in first] == [fact.fact_id for fact in second]
    assert [json.dumps(fact.to_json(), sort_keys=True) for fact in first] == [json.dumps(fact.to_json(), sort_keys=True) for fact in second]


def test_scan_emits_pipfile_unsupported_metadata_gap_and_lockfile_facts(tmp_path: Path) -> None:
    (tmp_path / "pyproject.toml").write_text(PYPROJECT, encoding="utf-8")
    (tmp_path / "uv.lock").write_text(UV_LOCK, encoding="utf-8")
    (tmp_path / "Pipfile").write_text("[packages]\nrequests = \"*\"\n", encoding="utf-8")
    (tmp_path / "app.py").write_text("import requests\n", encoding="utf-8")
    _git(tmp_path, "init")
    _git(tmp_path, "config", "user.email", "scan@example.invalid")
    _git(tmp_path, "config", "user.name", "scan")
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-m", "fixture")
    out = tmp_path / "scan-out"

    manifest, facts = scan(make_options(str(tmp_path), str(out)))

    gap_kinds = [fact.properties.get("gapKind") for fact in facts if fact.fact_type == "AnalysisGap"]
    assert "unsupported-metadata" in gap_kinds
    pipfile_gap = next(fact for fact in facts if fact.properties.get("gapKind") == "unsupported-metadata")
    assert pipfile_gap.rule_id == "python.package.metadata.v1"
    assert pipfile_gap.evidence.file_path == "Pipfile"
    lockfile_rows = [fact for fact in facts if fact.fact_type == "PackageReferenced" and fact.properties.get("sourceKind") == "lockfile"]
    assert {fact.properties["packageName"] for fact in lockfile_rows} == {"requests", "urllib3", "flask"}
    pipfile_packages = [fact for fact in lockfile_rows if fact.evidence.file_path == "Pipfile"]
    assert pipfile_packages == []
    ndjson = (out / "facts.ndjson").read_text(encoding="utf-8").splitlines()
    assert any('"gapKind":"unsupported-metadata"' in line for line in ndjson)
    assert any('"resolvedVersion":"2.32.3"' in line for line in ndjson)
    assert manifest.projects == ["Pipfile", "pyproject.toml"]


def _git(repo: Path, *arguments: str) -> None:
    subprocess.run(["git", *arguments], cwd=repo, check=True, capture_output=True, text=True)
