using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TraceMap.Core;

public static class CSharpSyntaxExtractor
{
    public static IReadOnlyList<CodeFact> Extract(string repoPath, ScanManifest manifest, IEnumerable<FileInventoryItem> inventory)
    {
        var facts = new List<CodeFact>();
        foreach (var file in inventory
            .Where(item => FileInventory.IsCSharpKind(item.Kind))
            .OrderBy(item => item.RelativePath, StringComparer.Ordinal))
        {
            var fullPath = Path.Combine(repoPath, file.RelativePath);
            if (TryGetBoilerplateCategory(file.RelativePath, out var boilerplateCategory))
            {
                facts.Add(CreateFileShapeFact(manifest, file.RelativePath, FactTypes.InfrastructureBoilerplate, boilerplateCategory));
            }

            if (IsGeneratedSource(fullPath))
            {
                continue;
            }

            try
            {
                var source = File.ReadAllText(fullPath);
                if (HasAutoGeneratedHeader(source))
                {
                    continue;
                }

                var tree = CSharpSyntaxTree.ParseText(SourceText.From(source), path: file.RelativePath);
                var root = tree.GetCompilationUnitRoot();
                AddParseDiagnostics(manifest, facts, tree);
                AddDeclarationFacts(manifest, facts, file.RelativePath, root);
                AddAttributeFacts(manifest, facts, file.RelativePath, root);
                AddMemberAccessFacts(manifest, facts, file.RelativePath, root);
                AddInvocationFacts(manifest, facts, file.RelativePath, root);
                AddObjectCreationFacts(manifest, facts, file.RelativePath, root);
                AddLogicShapeFacts(manifest, facts, file.RelativePath, root);
                AddQueryPatternFacts(manifest, facts, file.RelativePath, root);
                AddObjectShapeFacts(manifest, facts, file.RelativePath, root);
                AddAspNetRouteFacts(manifest, facts, file.RelativePath, root);
                AddRazorModelBindingTargetFacts(manifest, facts, file.RelativePath, root);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.AnalysisGap,
                    RuleIds.CSharpSyntaxDeclarations,
                    EvidenceTiers.Tier4Unknown,
                    new EvidenceSpan(file.RelativePath, 1, 1, null, "CSharpSyntaxExtractor", ScannerVersions.CSharpSyntaxExtractor),
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["message"] = $"Unable to read C# file for syntax extraction: {ex.Message}"
                    }));
            }
        }

        return facts;
    }

    private static void AddDeclarationFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var node in root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>())
        {
            switch (node)
            {
                case EnumDeclarationSyntax enumDeclaration:
                    facts.Add(CreateSyntaxFact(
                        manifest,
                        FactTypes.EnumDeclared,
                        RuleIds.CSharpSyntaxDeclarations,
                        filePath,
                        enumDeclaration,
                        targetSymbol: enumDeclaration.Identifier.ValueText,
                        properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                        {
                            ["name"] = enumDeclaration.Identifier.ValueText,
                            ["kind"] = "enum"
                        }));
                    break;
                case TypeDeclarationSyntax typeDeclaration:
                    var typeName = typeDeclaration.Identifier.ValueText;
                    facts.Add(CreateSyntaxFact(
                        manifest,
                        FactTypes.TypeDeclared,
                        RuleIds.CSharpSyntaxDeclarations,
                        filePath,
                        typeDeclaration,
                        targetSymbol: typeName,
                        properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                        {
                            ["name"] = typeName,
                            ["kind"] = typeDeclaration.Keyword.ValueText
                        }));
                    break;
            }
        }

        foreach (var method in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
        {
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.MethodDeclared,
                RuleIds.CSharpSyntaxDeclarations,
                filePath,
                method,
                targetSymbol: method.Identifier.ValueText,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["name"] = method.Identifier.ValueText
                }));
        }

        foreach (var property in root.DescendantNodes().OfType<PropertyDeclarationSyntax>())
        {
            var containingType = property.Ancestors().OfType<TypeDeclarationSyntax>().FirstOrDefault()?.Identifier.ValueText ?? string.Empty;
            var propertyName = property.Identifier.ValueText;
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.PropertyDeclared,
                RuleIds.CSharpSyntaxDeclarations,
                filePath,
                property,
                sourceSymbol: containingType,
                targetSymbol: string.IsNullOrWhiteSpace(containingType) ? propertyName : $"{containingType}.{propertyName}",
                contractElement: propertyName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["containingType"] = containingType,
                    ["declaredType"] = property.Type.ToString(),
                    ["modelKind"] = ModelKindForType(containingType),
                    ["name"] = propertyName,
                    ["propertyName"] = propertyName
                }));
        }
    }

    private static void AddAttributeFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var attribute in root.DescendantNodes().OfType<AttributeSyntax>())
        {
            var attributeName = attribute.Name.ToString();
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.AttributeUsed,
                RuleIds.CSharpSyntaxDeclarations,
                filePath,
                attribute,
                targetSymbol: attributeName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["name"] = attributeName
                }));
        }
    }

    private static void AddMemberAccessFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var memberAccess in root.DescendantNodes().OfType<MemberAccessExpressionSyntax>())
        {
            var memberName = memberAccess.Name.Identifier.ValueText;
            if (string.IsNullOrWhiteSpace(memberName))
            {
                memberName = memberAccess.Name.ToString();
            }

            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.MemberAccessName,
                RuleIds.CSharpSyntaxMemberAccess,
                filePath,
                memberAccess,
                sourceSymbol: GetSafeExpressionName(memberAccess.Expression),
                targetSymbol: memberName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["expressionHash"] = FactFactory.Hash(memberAccess.Expression.ToString(), 32),
                    ["expressionKind"] = memberAccess.Expression.Kind().ToString(),
                    ["memberName"] = memberName
                }));
        }
    }

    private static void AddInvocationFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            var invocationName = GetInvocationName(invocation.Expression);
            var containingMember = GetContainingMemberName(invocation);
            var receiverName = GetInvocationReceiverName(invocation.Expression);
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.InvocationName,
                RuleIds.CSharpSyntaxInvocation,
                filePath,
                invocation,
                targetSymbol: invocationName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["expressionHash"] = FactFactory.Hash(invocation.Expression.ToString(), 32),
                    ["expressionKind"] = invocation.Expression.Kind().ToString(),
                    ["invocationName"] = invocationName,
                    ["receiverName"] = receiverName ?? string.Empty
                }));

            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.CallEdge,
                RuleIds.CSharpSyntaxCallGraph,
                filePath,
                invocation,
                sourceSymbol: containingMember,
                targetSymbol: invocationName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["callerName"] = containingMember ?? string.Empty,
                    ["calleeName"] = invocationName,
                    ["callKind"] = "SyntaxInvocation"
                }));

            if (IsSerializationName(invocationName) || (receiverName?.Contains("Serializer", StringComparison.Ordinal) ?? false))
            {
                facts.Add(CreateSyntaxFact(
                    manifest,
                    FactTypes.SerializationLogic,
                    RuleIds.CSharpSyntaxLogicShape,
                    filePath,
                    invocation,
                    sourceSymbol: containingMember,
                    targetSymbol: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["callerName"] = containingMember ?? string.Empty,
                        ["operationName"] = invocationName
                    }));
            }
        }
    }

    private static void AddObjectCreationFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var creation in root.DescendantNodes().OfType<ObjectCreationExpressionSyntax>())
        {
            var typeName = creation.Type.ToString();
            var containingMember = GetContainingMemberName(creation);
            var assignedTo = GetAssignedVariableName(creation);
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.ObjectCreated,
                RuleIds.CSharpSyntaxObjectCreation,
                filePath,
                creation,
                sourceSymbol: containingMember,
                targetSymbol: typeName,
                contractElement: LastTypePart(typeName),
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["callerName"] = containingMember ?? string.Empty,
                    ["createdType"] = typeName,
                    ["assignedTo"] = assignedTo ?? string.Empty,
                    ["argumentCount"] = (creation.ArgumentList?.Arguments.Count ?? 0).ToString(),
                    ["creationKind"] = "SyntaxObjectCreation"
                }));

            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.CallEdge,
                RuleIds.CSharpSyntaxCallGraph,
                filePath,
                creation,
                sourceSymbol: containingMember,
                targetSymbol: typeName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["callerName"] = containingMember ?? string.Empty,
                    ["calleeName"] = typeName,
                    ["calleeContainingType"] = typeName,
                    ["callKind"] = "SyntaxObjectCreation",
                    ["assignedTo"] = assignedTo ?? string.Empty
                }));
        }
    }

    private static void AddLogicShapeFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var binary in root.DescendantNodes().OfType<BinaryExpressionSyntax>().Where(IsCalculationExpression))
        {
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.CalculationExpression,
                RuleIds.CSharpSyntaxLogicShape,
                filePath,
                binary,
                sourceSymbol: GetContainingMemberName(binary),
                targetSymbol: "calculation",
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["containingMember"] = GetContainingMemberName(binary) ?? string.Empty,
                    ["operator"] = binary.OperatorToken.ValueText,
                    ["expressionHash"] = FactFactory.Hash(binary.ToString(), 32)
                }));
        }

        foreach (var branch in root.DescendantNodes().Where(IsBranchingNode))
        {
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.BranchingLogic,
                RuleIds.CSharpSyntaxLogicShape,
                filePath,
                branch,
                sourceSymbol: GetContainingMemberName(branch),
                targetSymbol: branch.Kind().ToString(),
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["branchKind"] = branch.Kind().ToString(),
                    ["containingMember"] = GetContainingMemberName(branch) ?? string.Empty
                }));
        }

        foreach (var method in root.DescendantNodes().OfType<MethodDeclarationSyntax>().Where(method => LooksLikeRetryPolicyLogic(filePath, method)))
        {
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.RetryPolicyLogic,
                RuleIds.CSharpSyntaxLogicShape,
                filePath,
                method,
                sourceSymbol: method.Identifier.ValueText,
                targetSymbol: method.Identifier.ValueText,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["methodName"] = method.Identifier.ValueText,
                    ["className"] = method.Ancestors().OfType<TypeDeclarationSyntax>().FirstOrDefault()?.Identifier.ValueText ?? string.Empty,
                    ["matchedBy"] = "RetryBackoffNamingOrTimeSpan"
                }));
        }
    }

    private static void AddQueryPatternFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            if (invocation.Expression is not MemberAccessExpressionSyntax memberAccess)
            {
                continue;
            }

            var operationName = memberAccess.Name.Identifier.ValueText;
            if (!IsQueryOperation(operationName))
            {
                continue;
            }

            var fields = ExtractMemberNames(invocation.ArgumentList.Arguments.Select(argument => argument.Expression));
            var receiverName = GetSafeExpressionName(memberAccess.Expression) ?? string.Empty;
            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.QueryPatternDetected,
                RuleIds.CSharpSyntaxQueryPattern,
                EvidenceTiers.Tier3SyntaxOrTextual,
                ToEvidenceSpan(filePath, invocation),
                sourceSymbol: GetContainingMemberName(invocation),
                targetSymbol: operationName,
                contractElement: operationName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["operationName"] = operationName,
                    ["receiverName"] = receiverName,
                    ["filterFields"] = IsFilterOperation(operationName) ? string.Join(";", fields) : string.Empty,
                    ["sortFields"] = IsSortOperation(operationName) ? string.Join(";", fields) : string.Empty,
                    ["selectFields"] = operationName == "Select" ? string.Join(";", fields) : string.Empty,
                    ["includeFields"] = operationName == "Include" ? string.Join(";", fields) : string.Empty,
                    ["fieldCount"] = fields.Count.ToString(),
                    ["patternHash"] = FactFactory.Hash(invocation.ToString(), 32)
                }));
        }
    }

    private static void AddObjectShapeFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var creation in root.DescendantNodes().OfType<ObjectCreationExpressionSyntax>())
        {
            if (creation.Initializer is null)
            {
                continue;
            }

            var fields = ExtractInitializerFields(creation.Initializer);
            if (fields.Count == 0)
            {
                continue;
            }

            facts.Add(CreateObjectShapeFact(manifest, filePath, creation, creation.Type.ToString(), fields));
        }

        foreach (var anonymous in root.DescendantNodes().OfType<AnonymousObjectCreationExpressionSyntax>())
        {
            var fields = anonymous.Initializers
                .Select(initializer => initializer.NameEquals?.Name.Identifier.ValueText
                    ?? initializer.Expression switch
                    {
                        IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
                        MemberAccessExpressionSyntax memberAccess => memberAccess.Name.Identifier.ValueText,
                        _ => null
                    })
                .Where(name => !string.IsNullOrWhiteSpace(name))
                .Select(name => name!)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(name => name, StringComparer.Ordinal)
                .ToArray();
            if (fields.Length == 0)
            {
                continue;
            }

            facts.Add(CreateObjectShapeFact(manifest, filePath, anonymous, "anonymous", fields));
        }
    }

    private static void AddAspNetRouteFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var type in root.DescendantNodes().OfType<ClassDeclarationSyntax>().OrderBy(type => type.Identifier.ValueText, StringComparer.Ordinal))
        {
            var controllerName = GetControllerName(type);
            if (!LooksLikeController(type, controllerName))
            {
                continue;
            }

            var controllerRoutes = AttributeRoutes(type.AttributeLists, "Route").DefaultIfEmpty(string.Empty).ToArray();
            var controllerTokens = new SortedDictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["controller"] = controllerName,
                ["action"] = string.Empty
            };

            foreach (var method in type.Members.OfType<MethodDeclarationSyntax>().OrderBy(method => method.Identifier.ValueText, StringComparer.Ordinal))
            {
                var httpAttributes = HttpMethodAttributes(method.AttributeLists).ToArray();
                var methodRoutes = AttributeRoutes(method.AttributeLists, "Route").ToArray();
                if (httpAttributes.Length == 0 && methodRoutes.Length == 0)
                {
                    continue;
                }

                if (httpAttributes.Length == 0)
                {
                    httpAttributes = [new HttpAttribute("ANY", string.Empty)];
                }

                var methodTokens = new SortedDictionary<string, string>(controllerTokens, StringComparer.OrdinalIgnoreCase)
                {
                    ["action"] = method.Identifier.ValueText
                };
                var bodyParameters = LikelyBodyParameters(method).ToArray();
                foreach (var httpAttribute in httpAttributes)
                {
                    var routes = new List<string>();
                    if (!string.IsNullOrWhiteSpace(httpAttribute.Template))
                    {
                        routes.Add(httpAttribute.Template);
                    }
                    routes.AddRange(methodRoutes);
                    if (routes.Count == 0)
                    {
                        routes.Add(string.Empty);
                    }

                    foreach (var route in routes)
                    {
                        foreach (var controllerRoute in controllerRoutes)
                        {
                            var combinedRoute = CombineRouteTemplates(controllerRoute, route);
                            var normalized = EndpointRouteNormalizer.Normalize(combinedRoute, tokens: methodTokens);
                            facts.Add(FactFactory.Create(
                                manifest,
                                FactTypes.HttpRouteBinding,
                                RuleIds.CSharpSyntaxAspNetRoute,
                                EvidenceTiers.Tier3SyntaxOrTextual,
                                new EvidenceSpan(
                                    filePath,
                                    method.SyntaxTree.GetLineSpan(method.Span).StartLinePosition.Line + 1,
                                    Math.Max(
                                        method.SyntaxTree.GetLineSpan(method.Span).StartLinePosition.Line + 1,
                                        method.SyntaxTree.GetLineSpan(method.Span).EndLinePosition.Line + 1),
                                    null,
                                    "CSharpAspNetSyntaxRouteExtractor",
                                    ScannerVersions.CSharpAspNetSyntaxRouteExtractor),
                                sourceSymbol: $"{controllerName}Controller.{method.Identifier.ValueText}",
                                targetSymbol: $"{httpAttribute.Method} {normalized.PathTemplate}",
                                contractElement: normalized.PathTemplate,
                                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                                {
                                    ["methodName"] = httpAttribute.Method,
                                    ["httpMethods"] = httpAttribute.Method,
                                    ["routeTemplates"] = string.Join(",", new[] { controllerRoute, route }.Where(value => !string.IsNullOrWhiteSpace(value))),
                                    ["normalizedPathTemplate"] = normalized.PathTemplate,
                                    ["normalizedPathKey"] = normalized.PathKey,
                                    ["routeParameterNames"] = string.Join(";", normalized.ParameterNames),
                                    ["optionalParameterNames"] = string.Join(";", normalized.OptionalParameterNames),
                                    ["routeConstraints"] = string.Join(";", normalized.RouteConstraints),
                                    ["controllerName"] = controllerName,
                                    ["actionName"] = method.Identifier.ValueText,
                                    ["bodyParameterNames"] = string.Join(";", bodyParameters.Select(parameter => parameter.Name)),
                                    ["bodyParameterTypes"] = string.Join(";", bodyParameters.Select(parameter => parameter.Type)),
                                    ["authorizationKind"] = AuthorizationKind(type, method),
                                    ["staticMatchQuality"] = normalized.StaticMatchQuality
                                }));
                        }
                    }
                }
            }
        }
    }

    private static void AddRazorModelBindingTargetFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        var propertyMap = root.DescendantNodes()
            .OfType<ClassDeclarationSyntax>()
            .ToDictionary(
                type => type.Identifier.ValueText,
                type => type.Members
                    .OfType<PropertyDeclarationSyntax>()
                    .Where(property => !string.IsNullOrWhiteSpace(property.Identifier.ValueText))
                    .Select(property => new ModelProperty(property.Identifier.ValueText, property.Type.ToString(), property))
                    .OrderBy(property => property.Name, StringComparer.Ordinal)
                    .ToArray(),
                StringComparer.Ordinal);

        foreach (var type in root.DescendantNodes().OfType<ClassDeclarationSyntax>().OrderBy(type => type.Identifier.ValueText, StringComparer.Ordinal))
        {
            var controllerName = GetControllerName(type);
            var isController = LooksLikeController(type, controllerName);
            var isPageModel = LooksLikePageModel(type, filePath);

            if (isController)
            {
                foreach (var method in type.Members.OfType<MethodDeclarationSyntax>().OrderBy(method => method.Identifier.ValueText, StringComparer.Ordinal))
                {
                    var httpMethods = HttpMethodAttributes(method.AttributeLists)
                        .Select(attribute => attribute.Method)
                        .Concat(AttributeRoutes(method.AttributeLists, "Route").Any() ? ["ANY"] : [])
                        .Distinct(StringComparer.Ordinal)
                        .OrderBy(value => value, StringComparer.Ordinal)
                        .ToArray();
                    if (httpMethods.Length == 0)
                    {
                        continue;
                    }

                    foreach (var parameter in method.ParameterList.Parameters.OrderBy(parameter => parameter.Identifier.ValueText, StringComparer.Ordinal))
                    {
                        AddParameterBindingTargets(
                            manifest,
                            facts,
                            filePath,
                            parameter,
                            "action-parameter",
                            controllerName,
                            method.Identifier.ValueText,
                            null,
                            httpMethods,
                            propertyMap);
                    }
                }
            }

            if (isPageModel)
            {
                foreach (var method in type.Members.OfType<MethodDeclarationSyntax>()
                    .Where(method => method.Identifier.ValueText.StartsWith("On", StringComparison.Ordinal))
                    .OrderBy(method => method.Identifier.ValueText, StringComparer.Ordinal))
                {
                    foreach (var parameter in method.ParameterList.Parameters.OrderBy(parameter => parameter.Identifier.ValueText, StringComparer.Ordinal))
                    {
                        AddParameterBindingTargets(
                            manifest,
                            facts,
                            filePath,
                            parameter,
                            "handler-parameter",
                            null,
                            null,
                            method.Identifier.ValueText,
                            [PageHandlerHttpMethod(method.Identifier.ValueText)],
                            propertyMap);
                    }
                }
            }

            foreach (var property in type.Members.OfType<PropertyDeclarationSyntax>().OrderBy(property => property.Identifier.ValueText, StringComparer.Ordinal))
            {
                if (HasAttribute(property.AttributeLists, "BindProperty"))
                {
                    AddModelBindingFact(
                        manifest,
                        facts,
                        filePath,
                        property,
                        "bind-property",
                        "view-model",
                        type.Identifier.ValueText,
                        property.Identifier.ValueText,
                        property.Identifier.ValueText,
                        property.Type.ToString(),
                        null,
                        "form",
                        null,
                        null,
                        null,
                        "POST");
                }
                else if (isPageModel)
                {
                    AddModelBindingFact(
                        manifest,
                        facts,
                        filePath,
                        property,
                        "page-model",
                        "view-model",
                        type.Identifier.ValueText,
                        property.Identifier.ValueText,
                        property.Identifier.ValueText,
                        property.Type.ToString(),
                        null,
                        "unknown",
                        null,
                        null,
                        null,
                        string.Empty);
                }
            }

            if (LooksLikeViewModelType(type.Identifier.ValueText))
            {
                foreach (var property in type.Members.OfType<PropertyDeclarationSyntax>().OrderBy(property => property.Identifier.ValueText, StringComparer.Ordinal))
                {
                    AddModelBindingFact(
                        manifest,
                        facts,
                        filePath,
                        property,
                        "view-model",
                        "view-model",
                        type.Identifier.ValueText,
                        property.Identifier.ValueText,
                        property.Identifier.ValueText,
                        property.Type.ToString(),
                        null,
                        "unknown",
                        null,
                        null,
                        null,
                        string.Empty);
                }
            }
        }
    }

    private static void AddParameterBindingTargets(
        ScanManifest manifest,
        List<CodeFact> facts,
        string filePath,
        ParameterSyntax parameter,
        string bindingKind,
        string? controllerName,
        string? actionName,
        string? handlerName,
        IReadOnlyList<string> httpMethods,
        IReadOnlyDictionary<string, ModelProperty[]> propertyMap)
    {
        var parameterType = CleanTypeName(parameter.Type?.ToString() ?? string.Empty);
        if (!propertyMap.TryGetValue(LastTypePart(parameterType), out var properties) || properties.Length == 0)
        {
            if (IsLikelyModelBindingParameterType(parameterType))
            {
                AddModelBindingGap(
                    manifest,
                    facts,
                    filePath,
                    parameter,
                    "cross-file-parameter-type",
                    bindingKind,
                    LastTypePart(parameterType),
                    parameter.Identifier.ValueText,
                    ParameterSource(parameter),
                    controllerName,
                    actionName,
                    handlerName,
                    httpMethods);
            }

            return;
        }

        var parameterSource = ParameterSource(parameter);
        var modelKind = parameterSource == "body" || LooksLikeDtoType(parameterType)
            ? "dto"
            : parameterSource == "form" ? "view-model" : "model";
        foreach (var httpMethod in httpMethods)
        {
            foreach (var property in properties)
            {
                AddModelBindingFact(
                    manifest,
                    facts,
                    filePath,
                    parameter,
                    bindingKind,
                    modelKind,
                    LastTypePart(parameterType),
                    property.Name,
                    property.Name,
                    property.TypeName,
                    parameter.Identifier.ValueText,
                    parameterSource,
                    controllerName,
                    actionName,
                    handlerName,
                    httpMethod);
            }
        }
    }

    private static void AddModelBindingFact(
        ScanManifest manifest,
        List<CodeFact> facts,
        string filePath,
        SyntaxNode node,
        string bindingKind,
        string modelKind,
        string modelType,
        string propertyName,
        string propertyPath,
        string propertyType,
        string? parameterName,
        string parameterSource,
        string? controllerName,
        string? actionName,
        string? handlerName,
        string httpMethod)
    {
        var properties = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["bindingKind"] = bindingKind,
            ["httpMethod"] = httpMethod,
            ["modelKind"] = modelKind,
            ["modelType"] = modelType,
            ["parameterName"] = parameterName ?? string.Empty,
            ["parameterSource"] = parameterSource,
            ["propertyName"] = propertyName,
            ["propertyPath"] = propertyPath,
            ["propertyType"] = propertyType,
            ["uiFramework"] = "razor",
            ["valueStored"] = "safe-metadata-only"
        };
        if (!string.IsNullOrWhiteSpace(actionName))
        {
            properties["actionName"] = actionName!;
        }
        if (!string.IsNullOrWhiteSpace(controllerName))
        {
            properties["controllerName"] = controllerName!;
        }
        if (!string.IsNullOrWhiteSpace(handlerName))
        {
            properties["handlerName"] = handlerName!;
        }

        facts.Add(FactFactory.Create(
            manifest,
            FactTypes.RazorModelBindingTarget,
            RuleIds.RazorModelBinding,
            EvidenceTiers.Tier3SyntaxOrTextual,
            ToEvidenceSpan(filePath, node),
            sourceSymbol: actionName ?? handlerName ?? modelType,
            targetSymbol: $"{modelType}.{propertyName}",
            contractElement: propertyName,
            properties: properties));
    }

    private static void AddModelBindingGap(
        ScanManifest manifest,
        List<CodeFact> facts,
        string filePath,
        SyntaxNode node,
        string gapKind,
        string bindingKind,
        string modelType,
        string parameterName,
        string parameterSource,
        string? controllerName,
        string? actionName,
        string? handlerName,
        IReadOnlyList<string> httpMethods)
    {
        var properties = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["bindingKind"] = bindingKind,
            ["gapKind"] = gapKind,
            ["httpMethods"] = string.Join(";", httpMethods.OrderBy(value => value, StringComparer.Ordinal)),
            ["modelType"] = modelType,
            ["parameterName"] = parameterName,
            ["parameterSource"] = parameterSource,
            ["uiFramework"] = "razor",
            ["valueStored"] = "safe-metadata-only"
        };
        if (!string.IsNullOrWhiteSpace(actionName))
        {
            properties["actionName"] = actionName!;
        }
        if (!string.IsNullOrWhiteSpace(controllerName))
        {
            properties["controllerName"] = controllerName!;
        }
        if (!string.IsNullOrWhiteSpace(handlerName))
        {
            properties["handlerName"] = handlerName!;
        }

        facts.Add(FactFactory.Create(
            manifest,
            FactTypes.RazorBindingGap,
            RuleIds.RazorBindingGap,
            EvidenceTiers.Tier4Unknown,
            ToEvidenceSpan(filePath, node),
            sourceSymbol: actionName ?? handlerName ?? modelType,
            targetSymbol: modelType,
            contractElement: parameterName,
            properties: properties));
    }

    private static CodeFact CreateObjectShapeFact(ScanManifest manifest, string filePath, SyntaxNode node, string objectKind, IReadOnlyList<string> fields)
    {
        return FactFactory.Create(
            manifest,
            FactTypes.ObjectShapeInferred,
            RuleIds.CSharpSyntaxObjectShape,
            EvidenceTiers.Tier3SyntaxOrTextual,
            ToEvidenceSpan(filePath, node),
            sourceSymbol: GetContainingMemberName(node),
            targetSymbol: objectKind,
            contractElement: objectKind,
            properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
            {
                ["objectKind"] = objectKind,
                ["fieldNames"] = string.Join(";", fields),
                ["fieldCount"] = fields.Count.ToString(),
                ["shapeHash"] = FactFactory.Hash(string.Join("|", fields), 32),
                ["expressionHash"] = FactFactory.Hash(node.ToString(), 32)
            });
    }

    private static string GetInvocationName(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => string.IsNullOrWhiteSpace(memberAccess.Name.Identifier.ValueText)
                ? memberAccess.Name.ToString()
                : memberAccess.Name.Identifier.ValueText,
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax genericName => genericName.Identifier.ValueText,
            MemberBindingExpressionSyntax memberBinding => memberBinding.Name.Identifier.ValueText,
            _ => expression.Kind().ToString()
        };
    }

    private static string? GetInvocationReceiverName(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => GetSafeExpressionName(memberAccess.Expression),
            MemberBindingExpressionSyntax => "conditional-access",
            _ => null
        };
    }

    private static string? GetSafeExpressionName(ExpressionSyntax expression)
    {
        return expression switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax generic => generic.Identifier.ValueText,
            ThisExpressionSyntax => "this",
            BaseExpressionSyntax => "base",
            MemberAccessExpressionSyntax memberAccess when GetSafeExpressionName(memberAccess.Expression) is { Length: > 0 } receiver
                && GetSimpleName(memberAccess.Name) is { Length: > 0 } memberName => $"{receiver}.{memberName}",
            InvocationExpressionSyntax invocation => GetInvocationName(invocation.Expression),
            ConditionalAccessExpressionSyntax => "conditional-access",
            _ => null
        };
    }

    private static IReadOnlyList<string> ExtractMemberNames(IEnumerable<ExpressionSyntax> expressions)
    {
        return expressions
            .SelectMany(expression => expression.DescendantNodesAndSelf().OfType<MemberAccessExpressionSyntax>())
            .Select(member => member.Name.Identifier.ValueText)
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();
    }

    private static IReadOnlyList<string> ExtractInitializerFields(InitializerExpressionSyntax initializer)
    {
        return initializer.Expressions
            .Select(expression => expression switch
            {
                AssignmentExpressionSyntax assignment => assignment.Left switch
                {
                    IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
                    MemberAccessExpressionSyntax memberAccess => memberAccess.Name.Identifier.ValueText,
                    _ => null
                },
                _ => null
            })
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Select(name => name!)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();
    }

    private static bool IsQueryOperation(string operationName)
    {
        return operationName is "Where" or "OrderBy" or "OrderByDescending" or "ThenBy" or "ThenByDescending" or "Select" or "Include";
    }

    private static bool IsFilterOperation(string operationName)
    {
        return operationName is "Where";
    }

    private static bool IsSortOperation(string operationName)
    {
        return operationName is "OrderBy" or "OrderByDescending" or "ThenBy" or "ThenByDescending";
    }

    private static string? GetSimpleName(SimpleNameSyntax name)
    {
        return name switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax generic => generic.Identifier.ValueText,
            _ => null
        };
    }

    private static string? GetContainingMemberName(SyntaxNode node)
    {
        if (node.Ancestors().OfType<MethodDeclarationSyntax>().FirstOrDefault() is { } method)
        {
            return method.Identifier.ValueText;
        }

        if (node.Ancestors().OfType<ConstructorDeclarationSyntax>().FirstOrDefault() is { } constructor)
        {
            return constructor.Identifier.ValueText;
        }

        if (node.Ancestors().OfType<PropertyDeclarationSyntax>().FirstOrDefault() is { } property)
        {
            return property.Identifier.ValueText;
        }

        return null;
    }

    private static string? GetAssignedVariableName(ObjectCreationExpressionSyntax creation)
    {
        if (creation.Parent is EqualsValueClauseSyntax { Parent: VariableDeclaratorSyntax variable })
        {
            return variable.Identifier.ValueText;
        }

        if (creation.Parent is AssignmentExpressionSyntax assignment)
        {
            return GetSafeExpressionName(assignment.Left);
        }

        return null;
    }

    private static string LastTypePart(string value)
    {
        var withoutGeneric = value.Split('<', StringSplitOptions.TrimEntries)[0].Trim();
        var separator = Math.Max(withoutGeneric.LastIndexOf('.'), withoutGeneric.LastIndexOf(':'));
        return separator >= 0 && separator + 1 < withoutGeneric.Length
            ? withoutGeneric[(separator + 1)..]
            : withoutGeneric;
    }

    private static bool IsLikelyModelBindingParameterType(string typeName)
    {
        var value = LastTypePart(typeName);
        if (string.IsNullOrWhiteSpace(value))
        {
            return false;
        }

        var scalarTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "bool",
            "byte",
            "CancellationToken",
            "char",
            "DateOnly",
            "DateTime",
            "DateTimeOffset",
            "decimal",
            "double",
            "float",
            "Guid",
            "int",
            "long",
            "short",
            "string",
            "TimeOnly",
            "TimeSpan",
            "uint",
            "ulong",
            "ushort"
        };
        return !scalarTypes.Contains(value);
    }

    private static bool IsCalculationExpression(BinaryExpressionSyntax binary)
    {
        return binary.IsKind(SyntaxKind.MultiplyExpression)
            || binary.IsKind(SyntaxKind.DivideExpression)
            || binary.IsKind(SyntaxKind.ModuloExpression)
            || HasCalculationCall(binary)
            || HasNumericLiteral(binary);
    }

    private static bool HasCalculationCall(SyntaxNode node)
    {
        return node.DescendantNodesAndSelf()
            .OfType<MemberAccessExpressionSyntax>()
            .Any(memberAccess => memberAccess.Expression.ToString().Equals("Math", StringComparison.Ordinal)
                || memberAccess.Expression.ToString().Equals("TimeSpan", StringComparison.Ordinal));
    }

    private static bool HasNumericLiteral(SyntaxNode node)
    {
        return node.DescendantNodesAndSelf()
            .OfType<LiteralExpressionSyntax>()
            .Any(literal => literal.IsKind(SyntaxKind.NumericLiteralExpression));
    }

    private static bool IsBranchingNode(SyntaxNode node)
    {
        return node is IfStatementSyntax
            or SwitchStatementSyntax
            or ConditionalExpressionSyntax
            or ForStatementSyntax
            or ForEachStatementSyntax
            or WhileStatementSyntax
            or DoStatementSyntax;
    }

    private static bool LooksLikeRetryPolicyLogic(string filePath, MethodDeclarationSyntax method)
    {
        var className = method.Ancestors().OfType<TypeDeclarationSyntax>().FirstOrDefault()?.Identifier.ValueText ?? string.Empty;
        var signatureText = $"{filePath} {className} {method.Identifier.ValueText}";
        return signatureText.Contains("Retry", StringComparison.OrdinalIgnoreCase)
            || signatureText.Contains("Backoff", StringComparison.OrdinalIgnoreCase)
            || method.Identifier.ValueText.Equals("GetShouldRetry", StringComparison.Ordinal)
            || method.DescendantNodes().OfType<MemberAccessExpressionSyntax>().Any(memberAccess => memberAccess.Expression.ToString().Equals("TimeSpan", StringComparison.Ordinal));
    }

    private static bool IsSerializationName(string name)
    {
        return name.Contains("Serialize", StringComparison.OrdinalIgnoreCase)
            || name.Contains("Deserialize", StringComparison.OrdinalIgnoreCase);
    }

    private static void AddParseDiagnostics(ScanManifest manifest, List<CodeFact> facts, SyntaxTree tree)
    {
        foreach (var diagnostic in tree.GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .OrderBy(diagnostic => diagnostic.Location.GetLineSpan().StartLinePosition.Line)
            .ThenBy(diagnostic => diagnostic.Id, StringComparer.Ordinal))
        {
            var span = diagnostic.Location.GetLineSpan();
            var filePath = FileInventory.NormalizeRelativePath(span.Path);
            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.AnalysisGap,
                RuleIds.CSharpSyntaxDeclarations,
                EvidenceTiers.Tier4Unknown,
                new EvidenceSpan(
                    filePath,
                    span.StartLinePosition.Line + 1,
                    Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
                    null,
                    "CSharpSyntaxExtractor",
                    ScannerVersions.CSharpSyntaxExtractor),
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["diagnosticId"] = diagnostic.Id,
                    ["message"] = diagnostic.GetMessage()
                }));
        }
    }

    private static CodeFact CreateSyntaxFact(
        ScanManifest manifest,
        string factType,
        string ruleId,
        string filePath,
        SyntaxNode node,
        string? sourceSymbol = null,
        string? targetSymbol = null,
        string? contractElement = null,
        IReadOnlyDictionary<string, string>? properties = null)
    {
        return FactFactory.Create(
            manifest,
            factType,
            ruleId,
            EvidenceTiers.Tier3SyntaxOrTextual,
            ToEvidenceSpan(filePath, node),
            sourceSymbol: sourceSymbol,
            targetSymbol: targetSymbol,
            contractElement: contractElement,
            properties: properties);
    }

    private static CodeFact CreateFileShapeFact(ScanManifest manifest, string filePath, string factType, string category)
    {
        return FactFactory.Create(
            manifest,
            factType,
            RuleIds.CSharpSyntaxLogicShape,
            EvidenceTiers.Tier2Structural,
            new EvidenceSpan(filePath, 1, 1, null, "CSharpSyntaxExtractor", ScannerVersions.CSharpSyntaxExtractor),
            targetSymbol: category,
            properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
            {
                ["category"] = category,
                ["path"] = filePath
            });
    }

    private static EvidenceSpan ToEvidenceSpan(string filePath, SyntaxNode node)
    {
        var span = node.SyntaxTree.GetLineSpan(node.Span);
        return new EvidenceSpan(
            filePath,
            span.StartLinePosition.Line + 1,
            Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
            null,
            "CSharpSyntaxExtractor",
            ScannerVersions.CSharpSyntaxExtractor);
    }

    private static bool LooksLikeController(ClassDeclarationSyntax type, string controllerName)
    {
        return type.Identifier.ValueText.EndsWith("Controller", StringComparison.Ordinal)
            || HasAttribute(type.AttributeLists, "ApiController")
            || AttributeRoutes(type.AttributeLists, "Route").Any()
            || type.BaseList?.Types.Any(baseType => baseType.Type.ToString().Contains("Controller", StringComparison.Ordinal)) == true
            || !string.IsNullOrWhiteSpace(controllerName) && type.Members.OfType<MethodDeclarationSyntax>().Any(method => HttpMethodAttributes(method.AttributeLists).Any());
    }

    private static string GetControllerName(ClassDeclarationSyntax type)
    {
        var name = type.Identifier.ValueText;
        return name.EndsWith("Controller", StringComparison.Ordinal)
            ? name[..^"Controller".Length]
            : name;
    }

    private static IEnumerable<string> AttributeRoutes(SyntaxList<AttributeListSyntax> attributeLists, string attributeName)
    {
        foreach (var attribute in AttributesNamed(attributeLists, attributeName))
        {
            if (TryGetLiteralAttributeArgument(attribute, out var route))
            {
                yield return route;
            }
        }
    }

    private static IEnumerable<HttpAttribute> HttpMethodAttributes(SyntaxList<AttributeListSyntax> attributeLists)
    {
        foreach (var attribute in attributeLists.SelectMany(list => list.Attributes))
        {
            var name = SimplifyAttributeName(attribute.Name.ToString());
            var method = name switch
            {
                "HttpGet" => "GET",
                "HttpPost" => "POST",
                "HttpPut" => "PUT",
                "HttpPatch" => "PATCH",
                "HttpDelete" => "DELETE",
                "HttpHead" => "HEAD",
                "HttpOptions" => "OPTIONS",
                _ => null
            };
            if (method is null)
            {
                continue;
            }

            yield return new HttpAttribute(method, TryGetLiteralAttributeArgument(attribute, out var route) ? route : string.Empty);
        }
    }

    private static IEnumerable<AttributeSyntax> AttributesNamed(SyntaxList<AttributeListSyntax> attributeLists, string name)
    {
        return attributeLists
            .SelectMany(list => list.Attributes)
            .Where(attribute => SimplifyAttributeName(attribute.Name.ToString()).Equals(name, StringComparison.Ordinal));
    }

    private static bool HasAttribute(SyntaxList<AttributeListSyntax> attributeLists, string name)
    {
        return AttributesNamed(attributeLists, name).Any();
    }

    private static string SimplifyAttributeName(string value)
    {
        var simple = value.Split('.').Last();
        return simple.EndsWith("Attribute", StringComparison.Ordinal) ? simple[..^"Attribute".Length] : simple;
    }

    private static bool TryGetLiteralAttributeArgument(AttributeSyntax attribute, out string value)
    {
        value = string.Empty;
        var expression = attribute.ArgumentList?.Arguments.FirstOrDefault()?.Expression;
        if (expression is LiteralExpressionSyntax literal && literal.IsKind(SyntaxKind.StringLiteralExpression))
        {
            value = literal.Token.ValueText;
            return true;
        }

        return false;
    }

    private static string CombineRouteTemplates(string controllerRoute, string methodRoute)
    {
        if (methodRoute.StartsWith("~/", StringComparison.Ordinal) || methodRoute.StartsWith("/", StringComparison.Ordinal))
        {
            return methodRoute;
        }

        if (string.IsNullOrWhiteSpace(controllerRoute))
        {
            return methodRoute;
        }

        if (string.IsNullOrWhiteSpace(methodRoute))
        {
            return controllerRoute;
        }

        return $"{controllerRoute.TrimEnd('/')}/{methodRoute.TrimStart('/')}";
    }

    private static IEnumerable<(string Name, string Type)> LikelyBodyParameters(MethodDeclarationSyntax method)
    {
        foreach (var parameter in method.ParameterList.Parameters)
        {
            if (HasAttribute(parameter.AttributeLists, "FromRoute") || HasAttribute(parameter.AttributeLists, "FromQuery") || HasAttribute(parameter.AttributeLists, "FromHeader"))
            {
                continue;
            }

            var type = parameter.Type?.ToString() ?? string.Empty;
            if (HasAttribute(parameter.AttributeLists, "FromBody") || LooksLikeBodyType(type))
            {
                yield return (parameter.Identifier.ValueText, type);
            }
        }
    }

    private static string ParameterSource(ParameterSyntax parameter)
    {
        if (HasAttribute(parameter.AttributeLists, "FromBody"))
        {
            return "body";
        }

        if (HasAttribute(parameter.AttributeLists, "FromForm"))
        {
            return "form";
        }

        if (HasAttribute(parameter.AttributeLists, "FromRoute"))
        {
            return "route";
        }

        if (HasAttribute(parameter.AttributeLists, "FromQuery"))
        {
            return "query";
        }

        return LooksLikeBodyType(parameter.Type?.ToString() ?? string.Empty) ? "body" : "unknown";
    }

    private static bool LooksLikePageModel(ClassDeclarationSyntax type, string filePath)
    {
        return type.Identifier.ValueText.EndsWith("Model", StringComparison.Ordinal)
            && (filePath.Contains("/Pages/", StringComparison.OrdinalIgnoreCase)
                || type.BaseList?.Types.Any(baseType => baseType.Type.ToString().Contains("PageModel", StringComparison.Ordinal)) == true
                || type.Members.OfType<MethodDeclarationSyntax>().Any(method => method.Identifier.ValueText.StartsWith("OnGet", StringComparison.Ordinal) || method.Identifier.ValueText.StartsWith("OnPost", StringComparison.Ordinal)));
    }

    private static bool LooksLikeViewModelType(string typeName)
    {
        return typeName.EndsWith("ViewModel", StringComparison.Ordinal)
            || typeName.EndsWith("InputModel", StringComparison.Ordinal)
            || typeName.EndsWith("FormModel", StringComparison.Ordinal);
    }

    private static bool LooksLikeDtoType(string typeName)
    {
        return typeName.EndsWith("Dto", StringComparison.Ordinal)
            || typeName.EndsWith("Request", StringComparison.Ordinal)
            || typeName.EndsWith("Response", StringComparison.Ordinal)
            || typeName.EndsWith("Command", StringComparison.Ordinal);
    }

    private static string ModelKindForType(string typeName)
    {
        if (LooksLikeDtoType(typeName))
        {
            return "dto";
        }

        return LooksLikeViewModelType(typeName) ? "view-model" : "model";
    }

    private static string CleanTypeName(string typeName)
    {
        var clean = typeName.Trim().TrimEnd('?');
        if (clean.StartsWith("global::", StringComparison.Ordinal))
        {
            clean = clean["global::".Length..];
        }

        var genericStart = clean.IndexOf('<', StringComparison.Ordinal);
        if (genericStart >= 0)
        {
            clean = clean[..genericStart];
        }

        return clean;
    }

    private static string PageHandlerHttpMethod(string handlerName)
    {
        if (handlerName.StartsWith("OnPost", StringComparison.Ordinal))
        {
            return "POST";
        }

        if (handlerName.StartsWith("OnPut", StringComparison.Ordinal))
        {
            return "PUT";
        }

        if (handlerName.StartsWith("OnPatch", StringComparison.Ordinal))
        {
            return "PATCH";
        }

        if (handlerName.StartsWith("OnDelete", StringComparison.Ordinal))
        {
            return "DELETE";
        }

        return handlerName.StartsWith("OnGet", StringComparison.Ordinal) ? "GET" : "ANY";
    }

    private static bool LooksLikeBodyType(string type)
    {
        var lowered = type.Trim().ToLowerInvariant();
        if (string.IsNullOrWhiteSpace(lowered))
        {
            return false;
        }

        return !lowered.StartsWith("int", StringComparison.Ordinal)
            && !lowered.StartsWith("long", StringComparison.Ordinal)
            && !lowered.StartsWith("short", StringComparison.Ordinal)
            && !lowered.StartsWith("bool", StringComparison.Ordinal)
            && !lowered.StartsWith("string", StringComparison.Ordinal)
            && !lowered.StartsWith("guid", StringComparison.Ordinal)
            && !lowered.StartsWith("datetime", StringComparison.Ordinal)
            && !lowered.EndsWith("cancellationtoken", StringComparison.Ordinal);
    }

    private static string AuthorizationKind(ClassDeclarationSyntax type, MethodDeclarationSyntax method)
    {
        if (HasAttribute(method.AttributeLists, "AllowAnonymous"))
        {
            return "allow-anonymous";
        }

        if (HasAttribute(method.AttributeLists, "Authorize") || HasAttribute(type.AttributeLists, "Authorize"))
        {
            return "authorize";
        }

        return string.Empty;
    }

    private sealed record HttpAttribute(string Method, string Template);

    private sealed record ModelProperty(string Name, string TypeName, PropertyDeclarationSyntax Syntax);

    private static bool IsGeneratedSource(string fullPath)
    {
        var fileName = Path.GetFileName(fullPath);
        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool TryGetBoilerplateCategory(string relativePath, out string category)
    {
        var fileName = Path.GetFileName(relativePath);
        if (fileName.Equals("AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase))
        {
            category = "AssemblyMetadata";
            return true;
        }

        if (fileName.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase))
        {
            category = "GeneratedSource";
            return true;
        }

        if (relativePath.Contains("/obj/", StringComparison.OrdinalIgnoreCase)
            || relativePath.Contains("\\obj\\", StringComparison.OrdinalIgnoreCase))
        {
            category = "BuildOutput";
            return true;
        }

        if (relativePath.Contains("/Container/", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith("BuilderExtensions.cs", StringComparison.OrdinalIgnoreCase))
        {
            category = "DependencyInjectionGlue";
            return true;
        }

        category = string.Empty;
        return false;
    }

    private static bool HasAutoGeneratedHeader(string source)
    {
        var prefix = source.Length <= 512 ? source : source[..512];
        return prefix.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
            || prefix.Contains("This code was generated", StringComparison.OrdinalIgnoreCase);
    }
}
