using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TraceMap.Core;

public static class CSharpIntegrationSyntaxExtractor
{
    private static readonly HashSet<string> HttpClientMethods = new(StringComparer.Ordinal)
    {
        "GetAsync",
        "PostAsync",
        "PutAsync",
        "DeleteAsync",
        "SendAsync"
    };

    private static readonly HashSet<string> JsonHttpMethods = new(StringComparer.Ordinal)
    {
        "GetFromJsonAsync",
        "ReadFromJsonAsync",
        "PostAsJsonAsync",
        "PutAsJsonAsync"
    };

    private static readonly HashSet<string> DbSaveMethods = new(StringComparer.Ordinal)
    {
        "SaveChanges",
        "SaveChangesAsync"
    };

    private static readonly HashSet<string> DapperMethods = new(StringComparer.Ordinal)
    {
        "Query",
        "QueryAsync",
        "Execute",
        "ExecuteAsync"
    };

    private static readonly HashSet<string> EfRawSqlMethods = new(StringComparer.Ordinal)
    {
        "FromSqlRaw",
        "FromSql",
        "ExecuteSqlRaw",
        "SqlQueryRaw"
    };

    public static IReadOnlyList<CodeFact> Extract(string repoPath, ScanManifest manifest, IEnumerable<FileInventoryItem> inventory)
    {
        var facts = new List<CodeFact>();
        foreach (var file in inventory
            .Where(item => item.Kind == "CSharp")
            .OrderBy(item => item.RelativePath, StringComparer.Ordinal))
        {
            var fullPath = Path.Combine(repoPath, file.RelativePath);
            if (IsGeneratedSource(fullPath))
            {
                continue;
            }

            try
            {
                var source = File.ReadAllText(fullPath);
                if (HasAutoGeneratedHeader(source))
                {
                    continue;
                }

                var root = CSharpSyntaxTree.ParseText(SourceText.From(source), path: file.RelativePath).GetCompilationUnitRoot();
                AddDbContextFacts(manifest, facts, file.RelativePath, root);
                AddInvocationFacts(manifest, facts, file.RelativePath, root);
                AddSqlCommandFacts(manifest, facts, file.RelativePath, root);
                AddSqlStringFacts(manifest, facts, file.RelativePath, root);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.AnalysisGap,
                    RuleIds.DatabaseSqlText,
                    EvidenceTiers.Tier4Unknown,
                    new EvidenceSpan(file.RelativePath, 1, 1, null, "CSharpIntegrationSyntaxExtractor", ScannerVersions.CSharpIntegrationSyntaxExtractor),
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["message"] = $"Unable to read C# file for integration extraction: {ex.Message}"
                    }));
            }
        }

        return facts;
    }

    private static void AddDbContextFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var declaration in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
        {
            var baseTypeNames = declaration.BaseList?.Types.Select(type => type.Type.ToString()).ToArray() ?? [];
            var hasDbContextBase = baseTypeNames.Any(IsDbContextTypeName);
            var hasDbContextName = declaration.Identifier.ValueText.EndsWith("DbContext", StringComparison.Ordinal)
                || declaration.Identifier.ValueText.EndsWith("Context", StringComparison.Ordinal);

            if (hasDbContextBase || hasDbContextName)
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.DbContextDeclared,
                    RuleIds.DatabaseEntityFramework,
                    EvidenceTiers.Tier2Structural,
                    ToEvidenceSpan(filePath, declaration),
                    targetSymbol: declaration.Identifier.ValueText,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["className"] = declaration.Identifier.ValueText,
                        ["matchedBy"] = hasDbContextBase ? "BaseTypeName" : "ClassNamePattern",
                        ["baseTypes"] = string.Join(";", baseTypeNames.OrderBy(value => value, StringComparer.Ordinal))
                    }));
            }
        }

        foreach (var property in root.DescendantNodes().OfType<PropertyDeclarationSyntax>())
        {
            var typeName = property.Type.ToString();
            if (!IsDbSetTypeName(typeName))
            {
                continue;
            }

            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.DbSetDeclared,
                RuleIds.DatabaseEntityFramework,
                EvidenceTiers.Tier2Structural,
                ToEvidenceSpan(filePath, property),
                targetSymbol: property.Identifier.ValueText,
                contractElement: property.Identifier.ValueText,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["propertyName"] = property.Identifier.ValueText,
                    ["propertyType"] = typeName
                }));
        }
    }

    private static void AddInvocationFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            var invocationName = GetInvocationName(invocation.Expression);
            var receiverName = GetReceiver(invocation.Expression);
            if (HttpClientMethods.Contains(invocationName) || JsonHttpMethods.Contains(invocationName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.HttpCallDetected,
                    RuleIds.HttpClientInvocation,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: invocationName,
                    contractElement: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["methodName"] = invocationName,
                        ["methodFamily"] = HttpClientMethods.Contains(invocationName) ? "HttpClient" : "JsonHttpExtension",
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }

            if (invocationName == "CreateClient" && TryGetLiteralArgument(invocation, 0, out var clientName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.HttpClientCreated,
                    RuleIds.HttpClientInvocation,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: clientName,
                    contractElement: clientName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["clientName"] = clientName,
                        ["methodName"] = invocationName,
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }

            if (DbSaveMethods.Contains(invocationName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.DbChangeSaved,
                    RuleIds.DatabaseEntityFramework,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: invocationName,
                    contractElement: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["methodName"] = invocationName,
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }

            if (DapperMethods.Contains(invocationName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.DapperCallDetected,
                    RuleIds.DatabaseDapperInvocation,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: invocationName,
                    contractElement: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["methodName"] = invocationName,
                        ["receiverName"] = receiverName ?? string.Empty
                    }));

                AddDynamicSqlBoundaryIfNeeded(manifest, facts, filePath, invocation, invocationName);
            }

            if (EfRawSqlMethods.Contains(invocationName))
            {
                AddDynamicSqlBoundaryIfNeeded(manifest, facts, filePath, invocation, invocationName);
            }
        }
    }

    private static void AddSqlCommandFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var creation in root.DescendantNodes().OfType<ObjectCreationExpressionSyntax>())
        {
            var typeName = creation.Type.ToString();
            if (!IsSqlCommandTypeName(typeName))
            {
                continue;
            }

            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.SqlCommandDetected,
                RuleIds.DatabaseSqlText,
                EvidenceTiers.Tier3SyntaxOrTextual,
                ToEvidenceSpan(filePath, creation),
                targetSymbol: typeName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["typeName"] = typeName
                }));

            if (creation.ArgumentList is { Arguments.Count: > 0 }
                && !IsStaticStringLiteral(creation.ArgumentList.Arguments[0].Expression))
            {
                AddDynamicSqlBoundary(manifest, facts, filePath, creation, "SqlCommand");
            }
        }
    }

    private static void AddSqlStringFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var token in root.DescendantTokens().Where(IsStringLiteralToken))
        {
            var value = token.ValueText;
            if (!SqlTextDetector.IsSqlLike(value))
            {
                continue;
            }

            var containingSymbol = GetContainingSymbol(token.Parent, filePath);
            var containingType = GetContainingType(token.Parent);
            var containingMethod = GetContainingMemberName(token.Parent);
            var sourceKind = GetSqlSourceKind(token.Parent);
            var operationName = SqlShapeExtractor.OperationName(value);
            var textProperties = new SortedDictionary<string, string>(StringComparer.Ordinal)
            {
                ["textHash"] = FactFactory.Hash(value, 32),
                ["textLength"] = value.Length.ToString(),
                ["sqlSourceKind"] = sourceKind,
                ["targetSymbol"] = containingSymbol
            };
            if (!string.IsNullOrWhiteSpace(operationName))
            {
                textProperties["operationName"] = operationName;
            }

            if (!string.IsNullOrWhiteSpace(containingType))
            {
                textProperties["containingType"] = containingType;
            }

            if (!string.IsNullOrWhiteSpace(containingMethod))
            {
                textProperties["containingMethod"] = containingMethod;
            }

            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.SqlTextUsed,
                RuleIds.DatabaseSqlText,
                EvidenceTiers.Tier3SyntaxOrTextual,
                ToEvidenceSpan(filePath, token),
                sourceSymbol: containingMethod,
                targetSymbol: containingSymbol,
                properties: textProperties));

            var shapeProperties = SqlShapeExtractor.QueryShapeProperties(value, sourceKind);
            if (!string.IsNullOrWhiteSpace(containingType))
            {
                shapeProperties["containingType"] = containingType;
            }

            if (!string.IsNullOrWhiteSpace(containingMethod))
            {
                shapeProperties["containingMethod"] = containingMethod;
            }

            var target = shapeProperties.GetValueOrDefault("tableName") ?? containingSymbol;
            shapeProperties["targetSymbol"] = target;
            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.QueryPatternDetected,
                RuleIds.DatabaseSqlShape,
                EvidenceTiers.Tier3SyntaxOrTextual,
                ToEvidenceSpan(filePath, token),
                sourceSymbol: containingMethod,
                targetSymbol: target,
                contractElement: target,
                properties: shapeProperties));
        }
    }

    private static void AddDynamicSqlBoundaryIfNeeded(ScanManifest manifest, List<CodeFact> facts, string filePath, InvocationExpressionSyntax invocation, string methodName)
    {
        if (invocation.ArgumentList.Arguments.Count == 0)
        {
            return;
        }

        if (IsStaticStringLiteral(invocation.ArgumentList.Arguments[0].Expression))
        {
            return;
        }

        AddDynamicSqlBoundary(manifest, facts, filePath, invocation, methodName);
    }

    private static void AddDynamicSqlBoundary(ScanManifest manifest, List<CodeFact> facts, string filePath, SyntaxNode node, string methodName)
    {
        var containingSymbol = GetContainingSymbol(node, filePath);
        var containingMethod = GetContainingMemberName(node);
        facts.Add(FactFactory.Create(
            manifest,
            FactTypes.AnalysisGap,
            RuleIds.DatabaseSqlText,
            EvidenceTiers.Tier4Unknown,
            ToEvidenceSpan(filePath, node),
            sourceSymbol: containingMethod,
            targetSymbol: containingSymbol,
            properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
            {
                ["gapKind"] = "dynamic-sql-boundary",
                ["dynamicReason"] = "non-literal-sql-argument",
                ["methodName"] = methodName,
                ["sqlSourceKind"] = "dynamic-boundary",
                ["targetSymbol"] = containingSymbol,
                ["expressionHash"] = FactFactory.Hash(node.ToString(), 32)
            }));
    }

    private static string GetInvocationName(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => string.IsNullOrWhiteSpace(memberAccess.Name.Identifier.ValueText)
                ? memberAccess.Name.ToString()
                : memberAccess.Name.Identifier.ValueText,
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax genericName => genericName.Identifier.ValueText,
            MemberBindingExpressionSyntax memberBinding => memberBinding.Name.Identifier.ValueText,
            _ => expression.Kind().ToString()
        };
    }

    private static string? GetReceiver(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => GetSafeExpressionName(memberAccess.Expression),
            MemberBindingExpressionSyntax => "conditional-access",
            _ => null
        };
    }

    private static string? GetSafeExpressionName(ExpressionSyntax expression)
    {
        return expression switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax generic => generic.Identifier.ValueText,
            ThisExpressionSyntax => "this",
            BaseExpressionSyntax => "base",
            MemberAccessExpressionSyntax memberAccess when GetSafeExpressionName(memberAccess.Expression) is { Length: > 0 } receiver
                && GetSimpleName(memberAccess.Name) is { Length: > 0 } memberName => $"{receiver}.{memberName}",
            InvocationExpressionSyntax invocation => GetInvocationName(invocation.Expression),
            ConditionalAccessExpressionSyntax => "conditional-access",
            _ => null
        };
    }

    private static string? GetSimpleName(SimpleNameSyntax name)
    {
        return name switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax generic => generic.Identifier.ValueText,
            _ => null
        };
    }

    private static bool TryGetLiteralArgument(InvocationExpressionSyntax invocation, int index, out string value)
    {
        value = string.Empty;
        var arguments = invocation.ArgumentList.Arguments;
        if (arguments.Count <= index)
        {
            return false;
        }

        if (arguments[index].Expression is LiteralExpressionSyntax literal
            && IsStringLiteralToken(literal.Token)
            && literal.Token.ValueText is { Length: >= 0 } literalValue)
        {
            value = literalValue;
            return true;
        }

        return false;
    }

    private static bool IsStaticStringLiteral(ExpressionSyntax expression)
    {
        return expression is LiteralExpressionSyntax literal && IsStringLiteralToken(literal.Token);
    }

    private static string GetSqlSourceKind(SyntaxNode? node)
    {
        var invocation = node?.AncestorsAndSelf().OfType<InvocationExpressionSyntax>().FirstOrDefault();
        if (invocation is not null && EfRawSqlMethods.Contains(GetInvocationName(invocation.Expression)))
        {
            return "orm-text";
        }

        return "literal-string";
    }

    private static string GetContainingSymbol(SyntaxNode? node, string filePath)
    {
        return GetContainingMemberName(node)
            ?? GetContainingType(node)
            ?? FileInventory.NormalizeRelativePath(filePath);
    }

    private static string? GetContainingMemberName(SyntaxNode? node)
    {
        foreach (var ancestor in node?.AncestorsAndSelf() ?? [])
        {
            switch (ancestor)
            {
                case MethodDeclarationSyntax method:
                    return method.Identifier.ValueText;
                case ConstructorDeclarationSyntax constructor:
                    return constructor.Identifier.ValueText;
                case PropertyDeclarationSyntax property:
                    return property.Identifier.ValueText;
                case AccessorDeclarationSyntax accessor
                    when accessor.Parent?.Parent is PropertyDeclarationSyntax property:
                    return property.Identifier.ValueText;
            }
        }

        return null;
    }

    private static string? GetContainingType(SyntaxNode? node)
    {
        return node?.AncestorsAndSelf()
            .OfType<TypeDeclarationSyntax>()
            .FirstOrDefault()
            ?.Identifier
            .ValueText;
    }

    private static bool IsStringLiteralToken(SyntaxToken token)
    {
        return token.IsKind(SyntaxKind.StringLiteralToken)
            || token.IsKind(SyntaxKind.SingleLineRawStringLiteralToken)
            || token.IsKind(SyntaxKind.MultiLineRawStringLiteralToken)
            || token.IsKind(SyntaxKind.Utf8StringLiteralToken)
            || token.IsKind(SyntaxKind.Utf8SingleLineRawStringLiteralToken)
            || token.IsKind(SyntaxKind.Utf8MultiLineRawStringLiteralToken);
    }

    private static bool IsDbContextTypeName(string typeName)
    {
        return typeName.Equals("DbContext", StringComparison.Ordinal)
            || typeName.EndsWith(".DbContext", StringComparison.Ordinal)
            || typeName.EndsWith("EntityFrameworkCore.DbContext", StringComparison.Ordinal);
    }

    private static bool IsDbSetTypeName(string typeName)
    {
        return typeName.Equals("DbSet", StringComparison.Ordinal)
            || typeName.StartsWith("DbSet<", StringComparison.Ordinal)
            || typeName.EndsWith(".DbSet", StringComparison.Ordinal)
            || typeName.Contains(".DbSet<", StringComparison.Ordinal);
    }

    private static bool IsSqlCommandTypeName(string typeName)
    {
        return typeName.Equals("SqlCommand", StringComparison.Ordinal)
            || typeName.EndsWith(".SqlCommand", StringComparison.Ordinal);
    }

    private static EvidenceSpan ToEvidenceSpan(string filePath, SyntaxNode node)
    {
        var span = node.SyntaxTree.GetLineSpan(node.Span);
        return new EvidenceSpan(
            FileInventory.NormalizeRelativePath(filePath),
            span.StartLinePosition.Line + 1,
            Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
            null,
            "CSharpIntegrationSyntaxExtractor",
            ScannerVersions.CSharpIntegrationSyntaxExtractor);
    }

    private static EvidenceSpan ToEvidenceSpan(string filePath, SyntaxToken token)
    {
        var span = token.SyntaxTree!.GetLineSpan(token.Span);
        return new EvidenceSpan(
            FileInventory.NormalizeRelativePath(filePath),
            span.StartLinePosition.Line + 1,
            Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
            null,
            "CSharpIntegrationSyntaxExtractor",
            ScannerVersions.CSharpIntegrationSyntaxExtractor);
    }

    private static bool IsGeneratedSource(string fullPath)
    {
        var fileName = Path.GetFileName(fullPath);
        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasAutoGeneratedHeader(string source)
    {
        var prefix = source.Length <= 512 ? source : source[..512];
        return prefix.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
            || prefix.Contains("This code was generated", StringComparison.OrdinalIgnoreCase);
    }
}
