using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TraceMap.Core;

public static class CSharpIntegrationSyntaxExtractor
{
    private static readonly HashSet<string> HttpClientMethods = new(StringComparer.Ordinal)
    {
        "GetAsync",
        "PostAsync",
        "PutAsync",
        "DeleteAsync",
        "SendAsync"
    };

    private static readonly HashSet<string> JsonHttpMethods = new(StringComparer.Ordinal)
    {
        "GetFromJsonAsync",
        "ReadFromJsonAsync",
        "PostAsJsonAsync",
        "PutAsJsonAsync"
    };

    private static readonly HashSet<string> DbSaveMethods = new(StringComparer.Ordinal)
    {
        "SaveChanges",
        "SaveChangesAsync"
    };

    private static readonly HashSet<string> DapperMethods = new(StringComparer.Ordinal)
    {
        "Query",
        "QueryAsync",
        "Execute",
        "ExecuteAsync"
    };

    public static IReadOnlyList<CodeFact> Extract(string repoPath, ScanManifest manifest, IEnumerable<FileInventoryItem> inventory)
    {
        var facts = new List<CodeFact>();
        foreach (var file in inventory
            .Where(item => item.Kind == "CSharp")
            .OrderBy(item => item.RelativePath, StringComparer.Ordinal))
        {
            var fullPath = Path.Combine(repoPath, file.RelativePath);
            if (IsGeneratedSource(fullPath))
            {
                continue;
            }

            try
            {
                var source = File.ReadAllText(fullPath);
                if (HasAutoGeneratedHeader(source))
                {
                    continue;
                }

                var root = CSharpSyntaxTree.ParseText(SourceText.From(source), path: file.RelativePath).GetCompilationUnitRoot();
                AddDbContextFacts(manifest, facts, file.RelativePath, root);
                AddInvocationFacts(manifest, facts, file.RelativePath, root);
                AddSqlCommandFacts(manifest, facts, file.RelativePath, root);
                AddSqlStringFacts(manifest, facts, file.RelativePath, root);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.AnalysisGap,
                    RuleIds.DatabaseSqlText,
                    EvidenceTiers.Tier4Unknown,
                    new EvidenceSpan(file.RelativePath, 1, 1, null, "CSharpIntegrationSyntaxExtractor", ScannerVersions.CSharpIntegrationSyntaxExtractor),
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["message"] = $"Unable to read C# file for integration extraction: {ex.Message}"
                    }));
            }
        }

        return facts;
    }

    private static void AddDbContextFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var declaration in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
        {
            var baseTypeNames = declaration.BaseList?.Types.Select(type => type.Type.ToString()).ToArray() ?? [];
            var hasDbContextBase = baseTypeNames.Any(IsDbContextTypeName);
            var hasDbContextName = declaration.Identifier.ValueText.EndsWith("DbContext", StringComparison.Ordinal)
                || declaration.Identifier.ValueText.EndsWith("Context", StringComparison.Ordinal);

            if (hasDbContextBase || hasDbContextName)
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.DbContextDeclared,
                    RuleIds.DatabaseEntityFramework,
                    EvidenceTiers.Tier2Structural,
                    ToEvidenceSpan(filePath, declaration),
                    targetSymbol: declaration.Identifier.ValueText,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["className"] = declaration.Identifier.ValueText,
                        ["matchedBy"] = hasDbContextBase ? "BaseTypeName" : "ClassNamePattern",
                        ["baseTypes"] = string.Join(";", baseTypeNames.OrderBy(value => value, StringComparer.Ordinal))
                    }));
            }
        }

        foreach (var property in root.DescendantNodes().OfType<PropertyDeclarationSyntax>())
        {
            var typeName = property.Type.ToString();
            if (!IsDbSetTypeName(typeName))
            {
                continue;
            }

            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.DbSetDeclared,
                RuleIds.DatabaseEntityFramework,
                EvidenceTiers.Tier2Structural,
                ToEvidenceSpan(filePath, property),
                targetSymbol: property.Identifier.ValueText,
                contractElement: property.Identifier.ValueText,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["propertyName"] = property.Identifier.ValueText,
                    ["propertyType"] = typeName
                }));
        }
    }

    private static void AddInvocationFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            var invocationName = GetInvocationName(invocation.Expression);
            var receiverName = GetReceiver(invocation.Expression);
            if (HttpClientMethods.Contains(invocationName) || JsonHttpMethods.Contains(invocationName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.HttpCallDetected,
                    RuleIds.HttpClientInvocation,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: invocationName,
                    contractElement: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["methodName"] = invocationName,
                        ["methodFamily"] = HttpClientMethods.Contains(invocationName) ? "HttpClient" : "JsonHttpExtension",
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }

            if (invocationName == "CreateClient" && TryGetLiteralArgument(invocation, 0, out var clientName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.HttpClientCreated,
                    RuleIds.HttpClientInvocation,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: clientName,
                    contractElement: clientName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["clientName"] = clientName,
                        ["methodName"] = invocationName,
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }

            if (DbSaveMethods.Contains(invocationName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.DbChangeSaved,
                    RuleIds.DatabaseEntityFramework,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: invocationName,
                    contractElement: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["methodName"] = invocationName,
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }

            if (DapperMethods.Contains(invocationName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.DapperCallDetected,
                    RuleIds.DatabaseDapperInvocation,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: invocationName,
                    contractElement: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["methodName"] = invocationName,
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }
        }
    }

    private static void AddSqlCommandFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var creation in root.DescendantNodes().OfType<ObjectCreationExpressionSyntax>())
        {
            var typeName = creation.Type.ToString();
            if (!IsSqlCommandTypeName(typeName))
            {
                continue;
            }

            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.SqlCommandDetected,
                RuleIds.DatabaseSqlText,
                EvidenceTiers.Tier3SyntaxOrTextual,
                ToEvidenceSpan(filePath, creation),
                targetSymbol: typeName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["typeName"] = typeName
                }));
        }
    }

    private static void AddSqlStringFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var literal in root.DescendantNodes().OfType<LiteralExpressionSyntax>()
            .Where(IsStringLiteral))
        {
            var value = literal.Token.ValueText;
            if (!SqlTextDetector.IsSqlLike(value))
            {
                continue;
            }

            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.SqlTextUsed,
                RuleIds.DatabaseSqlText,
                EvidenceTiers.Tier3SyntaxOrTextual,
                ToEvidenceSpan(filePath, literal),
                targetSymbol: "sql-string-literal",
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["textHash"] = FactFactory.Hash(value, 32),
                    ["textLength"] = value.Length.ToString()
                }));
        }
    }

    private static string GetInvocationName(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => string.IsNullOrWhiteSpace(memberAccess.Name.Identifier.ValueText)
                ? memberAccess.Name.ToString()
                : memberAccess.Name.Identifier.ValueText,
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax genericName => genericName.Identifier.ValueText,
            MemberBindingExpressionSyntax memberBinding => memberBinding.Name.Identifier.ValueText,
            _ => expression.Kind().ToString()
        };
    }

    private static string? GetReceiver(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => GetSafeExpressionName(memberAccess.Expression),
            MemberBindingExpressionSyntax => "conditional-access",
            _ => null
        };
    }

    private static string? GetSafeExpressionName(ExpressionSyntax expression)
    {
        return expression switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax generic => generic.Identifier.ValueText,
            ThisExpressionSyntax => "this",
            BaseExpressionSyntax => "base",
            MemberAccessExpressionSyntax memberAccess when GetSafeExpressionName(memberAccess.Expression) is { Length: > 0 } receiver
                && GetSimpleName(memberAccess.Name) is { Length: > 0 } memberName => $"{receiver}.{memberName}",
            InvocationExpressionSyntax invocation => GetInvocationName(invocation.Expression),
            ConditionalAccessExpressionSyntax => "conditional-access",
            _ => null
        };
    }

    private static string? GetSimpleName(SimpleNameSyntax name)
    {
        return name switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax generic => generic.Identifier.ValueText,
            _ => null
        };
    }

    private static bool TryGetLiteralArgument(InvocationExpressionSyntax invocation, int index, out string value)
    {
        value = string.Empty;
        var arguments = invocation.ArgumentList.Arguments;
        if (arguments.Count <= index)
        {
            return false;
        }

        if (arguments[index].Expression is LiteralExpressionSyntax literal
            && IsStringLiteral(literal)
            && literal.Token.ValueText is { Length: >= 0 } literalValue)
        {
            value = literalValue;
            return true;
        }

        return false;
    }

    private static bool IsStringLiteral(LiteralExpressionSyntax literal)
    {
        return literal.IsKind(SyntaxKind.StringLiteralExpression);
    }

    private static bool IsDbContextTypeName(string typeName)
    {
        return typeName.Equals("DbContext", StringComparison.Ordinal)
            || typeName.EndsWith(".DbContext", StringComparison.Ordinal)
            || typeName.EndsWith("EntityFrameworkCore.DbContext", StringComparison.Ordinal);
    }

    private static bool IsDbSetTypeName(string typeName)
    {
        return typeName.Equals("DbSet", StringComparison.Ordinal)
            || typeName.StartsWith("DbSet<", StringComparison.Ordinal)
            || typeName.EndsWith(".DbSet", StringComparison.Ordinal)
            || typeName.Contains(".DbSet<", StringComparison.Ordinal);
    }

    private static bool IsSqlCommandTypeName(string typeName)
    {
        return typeName.Equals("SqlCommand", StringComparison.Ordinal)
            || typeName.EndsWith(".SqlCommand", StringComparison.Ordinal);
    }

    private static EvidenceSpan ToEvidenceSpan(string filePath, SyntaxNode node)
    {
        var span = node.SyntaxTree.GetLineSpan(node.Span);
        return new EvidenceSpan(
            FileInventory.NormalizeRelativePath(filePath),
            span.StartLinePosition.Line + 1,
            Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
            null,
            "CSharpIntegrationSyntaxExtractor",
            ScannerVersions.CSharpIntegrationSyntaxExtractor);
    }

    private static bool IsGeneratedSource(string fullPath)
    {
        var fileName = Path.GetFileName(fullPath);
        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasAutoGeneratedHeader(string source)
    {
        var prefix = source.Length <= 512 ? source : source[..512];
        return prefix.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
            || prefix.Contains("This code was generated", StringComparison.OrdinalIgnoreCase);
    }
}
