using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TraceMap.Core;

public static class CSharpIntegrationSyntaxExtractor
{
    private static readonly HashSet<string> HttpClientMethods = new(StringComparer.Ordinal)
    {
        "GetAsync",
        "PostAsync",
        "PutAsync",
        "DeleteAsync",
        "SendAsync"
    };

    private static readonly HashSet<string> JsonHttpMethods = new(StringComparer.Ordinal)
    {
        "GetFromJsonAsync",
        "ReadFromJsonAsync",
        "PostAsJsonAsync",
        "PutAsJsonAsync"
    };

    private static readonly HashSet<string> DbSaveMethods = new(StringComparer.Ordinal)
    {
        "SaveChanges",
        "SaveChangesAsync"
    };

    private static readonly HashSet<string> DapperMethods = new(StringComparer.Ordinal)
    {
        "Query",
        "QueryAsync",
        "Execute",
        "ExecuteAsync"
    };

    private static readonly HashSet<string> EfRawSqlMethods = new(StringComparer.Ordinal)
    {
        "FromSqlRaw",
        "FromSql",
        "ExecuteSqlRaw",
        "SqlQueryRaw"
    };

    private static readonly HashSet<string> MessagePublisherMethods = new(StringComparer.Ordinal)
    {
        "Publish",
        "PublishAsync",
        "PublishEventAsync",
        "Send",
        "SendAsync",
        "SendToQueue",
        "Produce",
        "ProduceAsync",
        "BasicPublish",
        "Enqueue",
        "EnqueueAsync",
        "QueueMessageAsync"
    };

    private static readonly HashSet<string> MessageConsumerMethods = new(StringComparer.Ordinal)
    {
        "Subscribe",
        "SubscribeAsync",
        "Consume",
        "ConsumeAsync",
        "BasicConsume",
        "Receive",
        "ReceiveAsync",
        "OnMessage",
        "OnMessageAsync"
    };

    private static readonly HashSet<string> MessageBindingMethods = new(StringComparer.Ordinal)
    {
        "QueueDeclare",
        "ExchangeDeclare",
        "Bind",
        "BindQueue",
        "ReceiveEndpoint"
    };

    public static IReadOnlyList<CodeFact> Extract(string repoPath, ScanManifest manifest, IEnumerable<FileInventoryItem> inventory)
    {
        var facts = new List<CodeFact>();
        foreach (var file in inventory
            .Where(item => FileInventory.IsCSharpKind(item.Kind))
            .OrderBy(item => item.RelativePath, StringComparer.Ordinal))
        {
            var fullPath = Path.Combine(repoPath, file.RelativePath);
            if (IsGeneratedSource(fullPath))
            {
                continue;
            }

            try
            {
                var source = File.ReadAllText(fullPath);
                if (HasAutoGeneratedHeader(source))
                {
                    continue;
                }

                var root = CSharpSyntaxTree.ParseText(SourceText.From(source), path: file.RelativePath).GetCompilationUnitRoot();
                AddDbContextFacts(manifest, facts, file.RelativePath, root);
                AddInvocationFacts(manifest, facts, file.RelativePath, root);
                AddMessageAttributeFacts(manifest, facts, file.RelativePath, root);
                AddSqlCommandFacts(manifest, facts, file.RelativePath, root);
                AddSqlStringFacts(manifest, facts, file.RelativePath, root);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.AnalysisGap,
                    RuleIds.DatabaseSqlText,
                    EvidenceTiers.Tier4Unknown,
                    new EvidenceSpan(file.RelativePath, 1, 1, null, "CSharpIntegrationSyntaxExtractor", ScannerVersions.CSharpIntegrationSyntaxExtractor),
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["message"] = $"Unable to read C# file for integration extraction: {ex.Message}"
                    }));
            }
        }

        return facts;
    }

    private static void AddDbContextFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var declaration in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
        {
            var baseTypeNames = declaration.BaseList?.Types.Select(type => type.Type.ToString()).ToArray() ?? [];
            var hasDbContextBase = baseTypeNames.Any(IsDbContextTypeName);
            var hasDbContextName = declaration.Identifier.ValueText.EndsWith("DbContext", StringComparison.Ordinal)
                || declaration.Identifier.ValueText.EndsWith("Context", StringComparison.Ordinal);

            if (hasDbContextBase || hasDbContextName)
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.DbContextDeclared,
                    RuleIds.DatabaseEntityFramework,
                    EvidenceTiers.Tier2Structural,
                    ToEvidenceSpan(filePath, declaration),
                    targetSymbol: declaration.Identifier.ValueText,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["className"] = declaration.Identifier.ValueText,
                        ["matchedBy"] = hasDbContextBase ? "BaseTypeName" : "ClassNamePattern",
                        ["baseTypes"] = string.Join(";", baseTypeNames.OrderBy(value => value, StringComparer.Ordinal))
                    }));
            }
        }

        foreach (var property in root.DescendantNodes().OfType<PropertyDeclarationSyntax>())
        {
            var typeName = property.Type.ToString();
            if (!IsDbSetTypeName(typeName))
            {
                continue;
            }

            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.DbSetDeclared,
                RuleIds.DatabaseEntityFramework,
                EvidenceTiers.Tier2Structural,
                ToEvidenceSpan(filePath, property),
                targetSymbol: property.Identifier.ValueText,
                contractElement: property.Identifier.ValueText,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["propertyName"] = property.Identifier.ValueText,
                    ["propertyType"] = typeName
                }));
        }
    }

    private static void AddInvocationFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        var constants = ExtractStringConstants(root);
        foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            var invocationName = GetInvocationName(invocation.Expression);
            var receiverName = GetReceiver(invocation.Expression);
            if (HttpClientMethods.Contains(invocationName) || JsonHttpMethods.Contains(invocationName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.HttpCallDetected,
                    RuleIds.HttpClientInvocation,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: invocationName,
                    contractElement: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["methodName"] = invocationName,
                        ["methodFamily"] = HttpClientMethods.Contains(invocationName) ? "HttpClient" : "JsonHttpExtension",
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }

            if (invocationName == "CreateClient" && TryGetLiteralArgument(invocation, 0, out var clientName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.HttpClientCreated,
                    RuleIds.HttpClientInvocation,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: clientName,
                    contractElement: clientName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["clientName"] = clientName,
                        ["methodName"] = invocationName,
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }

            if (DbSaveMethods.Contains(invocationName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.DbChangeSaved,
                    RuleIds.DatabaseEntityFramework,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: invocationName,
                    contractElement: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["methodName"] = invocationName,
                        ["receiverName"] = receiverName ?? string.Empty
                    }));
            }

            if (DapperMethods.Contains(invocationName))
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.DapperCallDetected,
                    RuleIds.DatabaseDapperInvocation,
                    EvidenceTiers.Tier3SyntaxOrTextual,
                    ToEvidenceSpan(filePath, invocation),
                    sourceSymbol: receiverName,
                    targetSymbol: invocationName,
                    contractElement: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["methodName"] = invocationName,
                        ["receiverName"] = receiverName ?? string.Empty
                    }));

                AddDynamicSqlBoundaryIfNeeded(manifest, facts, filePath, invocation, invocationName);
            }

            if (EfRawSqlMethods.Contains(invocationName))
            {
                AddDynamicSqlBoundaryIfNeeded(manifest, facts, filePath, invocation, invocationName);
            }

            AddMessageInvocationFact(manifest, facts, filePath, invocation, invocationName, receiverName, constants);
        }
    }

    private static void AddMessageInvocationFact(
        ScanManifest manifest,
        List<CodeFact> facts,
        string filePath,
        InvocationExpressionSyntax invocation,
        string invocationName,
        string? receiverName,
        IReadOnlyDictionary<string, string?> constants)
    {
        if (IsInProcessMediatorInvocation(invocationName, receiverName, invocation))
        {
            return;
        }

        if (MessagePublisherMethods.Contains(invocationName))
        {
            var pattern = MessagePublisherPattern(invocationName, receiverName, invocation);
            if (pattern is null)
            {
                return;
            }

            AddMessageSurfaceFromInvocation(manifest, facts, filePath, invocation, pattern, constants);
            return;
        }

        if (MessageConsumerMethods.Contains(invocationName))
        {
            var pattern = MessageConsumerPattern(invocationName, receiverName, invocation);
            if (pattern is null)
            {
                return;
            }

            AddMessageSurfaceFromInvocation(manifest, facts, filePath, invocation, pattern, constants);
            return;
        }

        if (MessageBindingMethods.Contains(invocationName))
        {
            var pattern = MessageBindingPattern(invocationName, receiverName, invocation);
            if (pattern is null)
            {
                return;
            }

            AddMessageSurfaceFromInvocation(manifest, facts, filePath, invocation, pattern, constants);
        }
    }

    private static void AddMessageSurfaceFromInvocation(
        ScanManifest manifest,
        List<CodeFact> facts,
        string filePath,
        InvocationExpressionSyntax invocation,
        MessagePattern pattern,
        IReadOnlyDictionary<string, string?> constants)
    {
        pattern = NormalizeMessagePatternForInvocation(pattern, invocation, constants);
        var destination = TryGetStaticString(invocation.ArgumentList.Arguments, pattern.DestinationArgumentIndex, constants, out var rawDestination)
            ? MessageSurfaceIdentity.FromRaw(rawDestination)
            : new MessageDestinationIdentity("dynamic", null, MessageSurfaceIdentity.Sha256(invocation.ToString()), "dynamic-destination");

        var evidence = ToEvidenceSpan(filePath, invocation);
        // Hashed identities are still useful static surfaces: the raw unsafe
        // destination is omitted, but the full digest keeps matching deterministic.
        if (ShouldEmitMessageGap(destination))
        {
            AddMessageGap(manifest, facts, evidence, pattern, destination, GetContainingMemberName(invocation), GetContainingType(invocation), manifest.RepoName);
            return;
        }

        AddMessageSurface(manifest, facts, evidence, pattern, destination, GetContainingMemberName(invocation), GetContainingType(invocation), manifest.RepoName);
    }

    private static void AddMessageAttributeFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        var constants = ExtractStringConstants(root);
        foreach (var attribute in root.DescendantNodes().OfType<AttributeSyntax>())
        {
            var attributeName = attribute.Name.ToString();
            var arguments = attribute.ArgumentList?.Arguments ?? default(SeparatedSyntaxList<AttributeArgumentSyntax>);
            var pattern = MessageAttributePattern(attributeName, arguments);
            if (pattern is null)
            {
                continue;
            }

            var destination = TryGetStaticString(arguments, pattern.DestinationArgumentIndex, constants, out var rawDestination)
                ? MessageSurfaceIdentity.FromRaw(rawDestination)
                : new MessageDestinationIdentity("dynamic", null, MessageSurfaceIdentity.Sha256(attribute.ToString()), "dynamic-destination");
            var evidence = ToEvidenceSpan(filePath, attribute);
            if (ShouldEmitMessageGap(destination))
            {
                AddMessageGap(manifest, facts, evidence, pattern, destination, GetContainingMemberName(attribute), GetContainingType(attribute), manifest.RepoName);
                continue;
            }

            AddMessageSurface(manifest, facts, evidence, pattern, destination, GetContainingMemberName(attribute), GetContainingType(attribute), manifest.RepoName);
        }
    }

    private static MessagePattern NormalizeMessagePatternForInvocation(
        MessagePattern pattern,
        InvocationExpressionSyntax invocation,
        IReadOnlyDictionary<string, string?> constants)
    {
        if (pattern.FrameworkFamily == "rabbitmq"
            && pattern.FrameworkFeature == "basic-publish"
            && TryGetStaticString(invocation.ArgumentList.Arguments, 0, constants, out var exchange)
            && string.IsNullOrEmpty(exchange))
        {
            return pattern with
            {
                FrameworkFeature = "basic-publish-default-exchange",
                SurfaceKind = "message-queue",
                DestinationArgumentIndex = 1
            };
        }

        return pattern;
    }

    private static bool ShouldEmitMessageGap(MessageDestinationIdentity destination)
    {
        if (destination.Status is "dynamic" or "unknown" or "ambiguous")
        {
            return true;
        }

        return destination.GapReason is not null && destination.Status != "hashed";
    }

    private static void AddMessageSurface(
        ScanManifest manifest,
        List<CodeFact> facts,
        EvidenceSpan evidence,
        MessagePattern pattern,
        MessageDestinationIdentity destination,
        string? containingMethod,
        string? containingType,
        string sourceLabel)
    {
        var metadata = MessageMetadata(pattern, destination, evidence, containingMethod, containingType, sourceLabel);
        facts.Add(FactFactory.Create(
            manifest,
            pattern.FactType,
            pattern.RuleId,
            pattern.EvidenceTier,
            evidence,
            sourceSymbol: containingMethod,
            targetSymbol: destination.NormalizedDestinationKey ?? destination.DestinationHash ?? pattern.OperationKind,
            contractElement: destination.NormalizedDestinationKey ?? destination.DestinationHash,
            properties: metadata));
    }

    private static void AddMessageGap(
        ScanManifest manifest,
        List<CodeFact> facts,
        EvidenceSpan evidence,
        MessagePattern pattern,
        MessageDestinationIdentity destination,
        string? containingMethod,
        string? containingType,
        string sourceLabel)
    {
        var metadata = MessageMetadata(pattern, destination, evidence, containingMethod, containingType, sourceLabel);
        metadata["gapKind"] = "message-surface";
        metadata["gapReason"] = destination.GapReason ?? "missing-destination-identity";
        metadata["message"] = "Message surface evidence was visible, but TraceMap could not derive a safe static destination identity.";
        facts.Add(FactFactory.Create(
            manifest,
            FactTypes.AnalysisGap,
            RuleIds.MessageSurfaceGap,
            EvidenceTiers.Tier4Unknown,
            evidence,
            sourceSymbol: containingMethod,
            targetSymbol: containingType,
            properties: metadata));
    }

    private static SortedDictionary<string, string> MessageMetadata(
        MessagePattern pattern,
        MessageDestinationIdentity destination,
        EvidenceSpan evidence,
        string? containingMethod,
        string? containingType,
        string sourceLabel)
    {
        var metadata = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["frameworkFamily"] = pattern.FrameworkFamily,
            ["frameworkFeature"] = pattern.FrameworkFeature,
            ["operationDirection"] = pattern.OperationDirection,
            ["operationKind"] = pattern.OperationKind,
            ["surfaceKind"] = pattern.SurfaceKind,
            ["destinationIdentityStatus"] = destination.Status,
            ["ruleLimitations"] = "static-message-evidence-only;no-runtime-delivery-or-topology-claim"
        };
        if (!string.IsNullOrWhiteSpace(destination.NormalizedDestinationKey))
        {
            metadata["normalizedDestinationKey"] = destination.NormalizedDestinationKey!;
        }

        if (!string.IsNullOrWhiteSpace(destination.DestinationHash))
        {
            metadata["destinationHash"] = destination.DestinationHash!;
        }

        var stableKeyMetadataHash = MessageSurfaceIdentity.SafeMetadataHash(metadata);

        if (!string.IsNullOrWhiteSpace(containingMethod))
        {
            metadata[pattern.OperationDirection == "consume" ? "handlerSymbolId" : "publisherSymbolId"] = containingMethod!;
            metadata["containingMethod"] = containingMethod!;
        }

        if (!string.IsNullOrWhiteSpace(containingType))
        {
            metadata["containingType"] = containingType!;
        }

        metadata["safeMetadataHash"] = stableKeyMetadataHash;
        // Static destination-backed keys intentionally exclude file/line and handler
        // identity so small refactors do not churn cross-scan surface identity.
        var occurrenceDiscriminator = destination.Status == "static"
            ? null
            : MessageSurfaceIdentity.OccurrenceDiscriminator(evidence.FilePath, evidence.StartLine, evidence.EndLine, pattern.RuleId, stableKeyMetadataHash);
        metadata["stableMessageSurfaceKey"] = MessageSurfaceIdentity.StableKey(
            sourceLabel,
            "csharp",
            pattern.SurfaceKind,
            pattern.FrameworkFamily,
            pattern.OperationDirection,
            pattern.OperationKind,
            destination.Status,
            destination.NormalizedDestinationKey,
            destination.DestinationHash,
            null,
            occurrenceDiscriminator,
            stableKeyMetadataHash);
        return metadata;
    }

    private static void AddSqlCommandFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var creation in root.DescendantNodes().OfType<ObjectCreationExpressionSyntax>())
        {
            var typeName = creation.Type.ToString();
            if (!IsSqlCommandTypeName(typeName))
            {
                continue;
            }

            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.SqlCommandDetected,
                RuleIds.DatabaseSqlText,
                EvidenceTiers.Tier3SyntaxOrTextual,
                ToEvidenceSpan(filePath, creation),
                targetSymbol: typeName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["typeName"] = typeName
                }));

            if (creation.ArgumentList is { Arguments.Count: > 0 }
                && !IsStaticStringLiteral(creation.ArgumentList.Arguments[0].Expression))
            {
                AddDynamicSqlBoundary(manifest, facts, filePath, creation, "SqlCommand");
            }
        }
    }

    private static void AddSqlStringFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var token in root.DescendantTokens().Where(IsStringLiteralToken))
        {
            var value = token.ValueText;
            if (!SqlTextDetector.IsSqlLike(value))
            {
                continue;
            }

            var containingType = GetContainingType(token.Parent);
            var containingMethod = GetContainingMemberName(token.Parent);
            var containingSymbol = ContainingSymbol(filePath, containingType, containingMethod);
            var sourceKind = GetSqlSourceKind(token.Parent);
            var operationName = SqlShapeExtractor.OperationName(value);
            var textProperties = new SortedDictionary<string, string>(StringComparer.Ordinal)
            {
                ["textHash"] = FactFactory.Hash(value, 32),
                ["textLength"] = value.Length.ToString(),
                ["sqlSourceKind"] = sourceKind,
                ["targetSymbol"] = containingSymbol
            };
            if (!string.IsNullOrWhiteSpace(operationName))
            {
                textProperties["operationName"] = operationName;
            }

            if (!string.IsNullOrWhiteSpace(containingType))
            {
                textProperties["containingType"] = containingType;
            }

            if (!string.IsNullOrWhiteSpace(containingMethod))
            {
                textProperties["containingMethod"] = containingMethod;
            }

            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.SqlTextUsed,
                RuleIds.DatabaseSqlText,
                EvidenceTiers.Tier3SyntaxOrTextual,
                ToEvidenceSpan(filePath, token),
                sourceSymbol: containingMethod,
                targetSymbol: containingSymbol,
                properties: textProperties));

            var shapeProperties = SqlShapeExtractor.QueryShapeProperties(value, sourceKind);
            if (!string.IsNullOrWhiteSpace(containingType))
            {
                shapeProperties["containingType"] = containingType;
            }

            if (!string.IsNullOrWhiteSpace(containingMethod))
            {
                shapeProperties["containingMethod"] = containingMethod;
            }

            if (!shapeProperties.ContainsKey("queryShapeHash"))
            {
                continue;
            }

            var target = shapeProperties.GetValueOrDefault("tableName") ?? containingSymbol;
            shapeProperties["targetSymbol"] = target;
            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.QueryPatternDetected,
                RuleIds.DatabaseSqlShape,
                EvidenceTiers.Tier3SyntaxOrTextual,
                ToEvidenceSpan(filePath, token),
                sourceSymbol: containingMethod,
                targetSymbol: target,
                contractElement: target,
                properties: shapeProperties));
        }
    }

    private static void AddDynamicSqlBoundaryIfNeeded(ScanManifest manifest, List<CodeFact> facts, string filePath, InvocationExpressionSyntax invocation, string methodName)
    {
        if (invocation.ArgumentList.Arguments.Count == 0)
        {
            return;
        }

        if (IsStaticStringLiteral(invocation.ArgumentList.Arguments[0].Expression))
        {
            return;
        }

        AddDynamicSqlBoundary(manifest, facts, filePath, invocation, methodName);
    }

    private static void AddDynamicSqlBoundary(ScanManifest manifest, List<CodeFact> facts, string filePath, SyntaxNode node, string methodName)
    {
        var containingType = GetContainingType(node);
        var containingMethod = GetContainingMemberName(node);
        var containingSymbol = ContainingSymbol(filePath, containingType, containingMethod);
        facts.Add(FactFactory.Create(
            manifest,
            FactTypes.AnalysisGap,
            RuleIds.DatabaseSqlText,
            EvidenceTiers.Tier4Unknown,
            ToEvidenceSpan(filePath, node),
            sourceSymbol: containingMethod,
            targetSymbol: containingSymbol,
            properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
            {
                ["gapKind"] = "dynamic-sql-boundary",
                ["dynamicReason"] = "non-literal-sql-argument",
                ["methodName"] = methodName,
                ["sqlSourceKind"] = "dynamic-boundary",
                ["targetSymbol"] = containingSymbol,
                ["expressionHash"] = FactFactory.Hash(node.ToString(), 32)
            }));
    }

    private static string GetInvocationName(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => string.IsNullOrWhiteSpace(memberAccess.Name.Identifier.ValueText)
                ? memberAccess.Name.ToString()
                : memberAccess.Name.Identifier.ValueText,
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax genericName => genericName.Identifier.ValueText,
            MemberBindingExpressionSyntax memberBinding => memberBinding.Name.Identifier.ValueText,
            _ => expression.Kind().ToString()
        };
    }

    private static string? GetReceiver(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => GetSafeExpressionName(memberAccess.Expression),
            MemberBindingExpressionSyntax => "conditional-access",
            _ => null
        };
    }

    private static string? GetSafeExpressionName(ExpressionSyntax expression)
    {
        return expression switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax generic => generic.Identifier.ValueText,
            ThisExpressionSyntax => "this",
            BaseExpressionSyntax => "base",
            MemberAccessExpressionSyntax memberAccess when GetSafeExpressionName(memberAccess.Expression) is { Length: > 0 } receiver
                && GetSimpleName(memberAccess.Name) is { Length: > 0 } memberName => $"{receiver}.{memberName}",
            InvocationExpressionSyntax invocation => GetInvocationName(invocation.Expression),
            ConditionalAccessExpressionSyntax => "conditional-access",
            _ => null
        };
    }

    private static string? GetSimpleName(SimpleNameSyntax name)
    {
        return name switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax generic => generic.Identifier.ValueText,
            _ => null
        };
    }

    private static MessagePattern? MessagePublisherPattern(string invocationName, string? receiverName, InvocationExpressionSyntax invocation)
    {
        if (invocationName is "PublishEventAsync")
        {
            return new MessagePattern(FactTypes.MessagePublisherSurface, RuleIds.MessageSurfacePublish, EvidenceTiers.Tier3SyntaxOrTextual, "dapr", "client-call", "publish", "publish", "message-topic", 1);
        }

        if (invocationName is "Produce" or "ProduceAsync")
        {
            return new MessagePattern(FactTypes.MessagePublisherSurface, RuleIds.MessageSurfacePublish, EvidenceTiers.Tier3SyntaxOrTextual, "kafka", "producer-call", "publish", "produce", "message-stream", 0);
        }

        if (invocationName is "SendToQueue" or "QueueMessageAsync" or "Enqueue" or "EnqueueAsync")
        {
            return new MessagePattern(FactTypes.MessagePublisherSurface, RuleIds.MessageSurfacePublish, EvidenceTiers.Tier3SyntaxOrTextual, "queue-client", "client-call", "publish", "enqueue", "message-queue", 0);
        }

        if (invocationName is "BasicPublish")
        {
            return new MessagePattern(FactTypes.MessagePublisherSurface, RuleIds.MessageSurfacePublish, EvidenceTiers.Tier3SyntaxOrTextual, "rabbitmq", "basic-publish", "publish", "publish", "message-exchange", 0);
        }

        if (invocationName is "Publish" or "PublishAsync")
        {
            if (LooksLikeExternalMessageReceiver(receiverName))
            {
                return new MessagePattern(FactTypes.MessagePublisherSurface, RuleIds.MessageSurfacePublish, EvidenceTiers.Tier3SyntaxOrTextual, FrameworkFromReceiver(receiverName), "publish-call", "publish", "publish", "message-topic", 0);
            }

            if (invocation.Expression is MemberAccessExpressionSyntax)
            {
                return null;
            }
        }

        if (invocationName is "Send" or "SendAsync")
        {
            if (LooksLikeExternalMessageReceiver(receiverName))
            {
                return new MessagePattern(FactTypes.MessagePublisherSurface, RuleIds.MessageSurfacePublish, EvidenceTiers.Tier3SyntaxOrTextual, FrameworkFromReceiver(receiverName), "send-call", "publish", "send", "message-queue", 0);
            }
        }

        return null;
    }

    private static MessagePattern? MessageConsumerPattern(string invocationName, string? receiverName, InvocationExpressionSyntax invocation)
    {
        if (invocationName is "BasicConsume" or "Receive" or "ReceiveAsync")
        {
            return new MessagePattern(FactTypes.MessageConsumerSurface, RuleIds.MessageSurfaceConsume, EvidenceTiers.Tier3SyntaxOrTextual, "queue-client", "consumer-call", "consume", "receive", "message-queue", 0);
        }

        if (invocationName is "Consume" or "ConsumeAsync")
        {
            return new MessagePattern(FactTypes.MessageConsumerSurface, RuleIds.MessageSurfaceConsume, EvidenceTiers.Tier3SyntaxOrTextual, FrameworkFromReceiver(receiverName), "consumer-call", "consume", "consume", "message-stream", 0);
        }

        if (invocationName is "Subscribe" or "SubscribeAsync" or "OnMessage" or "OnMessageAsync")
        {
            if (LooksLikeExternalMessageReceiver(receiverName) || invocationName.StartsWith("OnMessage", StringComparison.Ordinal))
            {
                return new MessagePattern(FactTypes.MessageConsumerSurface, RuleIds.MessageSurfaceConsume, EvidenceTiers.Tier3SyntaxOrTextual, FrameworkFromReceiver(receiverName), "subscribe-call", "consume", "subscribe", "message-topic", 0);
            }
        }

        return null;
    }

    private static MessagePattern? MessageBindingPattern(string invocationName, string? receiverName, InvocationExpressionSyntax invocation)
    {
        return invocationName switch
        {
            "QueueDeclare" => new MessagePattern(FactTypes.MessageBindingDeclared, RuleIds.MessageSurfaceBinding, EvidenceTiers.Tier3SyntaxOrTextual, "rabbitmq", "queue-declare", "declare", "declare", "message-queue", 0),
            "ExchangeDeclare" => new MessagePattern(FactTypes.MessageBindingDeclared, RuleIds.MessageSurfaceBinding, EvidenceTiers.Tier3SyntaxOrTextual, "rabbitmq", "exchange-declare", "declare", "declare", "message-exchange", 0),
            "Bind" or "BindQueue" => new MessagePattern(FactTypes.MessageBindingDeclared, RuleIds.MessageSurfaceBinding, EvidenceTiers.Tier3SyntaxOrTextual, FrameworkFromReceiver(receiverName), "binding-call", "bind", "bind", "message-channel", 0),
            "ReceiveEndpoint" => new MessagePattern(FactTypes.MessageBindingDeclared, RuleIds.MessageSurfaceBinding, EvidenceTiers.Tier3SyntaxOrTextual, "masstransit", "receive-endpoint", "bind", "bind", "message-queue", 0),
            _ => null
        };
    }

    private static MessagePattern? MessageAttributePattern(string attributeName, SeparatedSyntaxList<AttributeArgumentSyntax> arguments)
    {
        var name = attributeName.EndsWith("Attribute", StringComparison.Ordinal)
            ? attributeName[..^"Attribute".Length]
            : attributeName;
        return name switch
        {
            "QueueTrigger" => new MessagePattern(FactTypes.MessageConsumerSurface, RuleIds.MessageSurfaceConsume, EvidenceTiers.Tier2Structural, "azure-functions", "queue-trigger-attribute", "consume", "handle", "message-queue", 0),
            "ServiceBusTrigger" => new MessagePattern(FactTypes.MessageConsumerSurface, RuleIds.MessageSurfaceConsume, EvidenceTiers.Tier2Structural, "azure-functions", "servicebus-trigger-attribute", "consume", "handle", arguments.Count >= 2 ? "message-topic" : "message-queue", 0),
            "EventHubTrigger" => new MessagePattern(FactTypes.MessageConsumerSurface, RuleIds.MessageSurfaceConsume, EvidenceTiers.Tier2Structural, "azure-functions", "eventhub-trigger-attribute", "consume", "handle", "message-stream", 0),
            "TimerTrigger" => new MessagePattern(FactTypes.MessageBindingDeclared, RuleIds.MessageSurfaceBinding, EvidenceTiers.Tier2Structural, "azure-functions", "timer-trigger-attribute", "declare", "bind", "message-event", 0),
            "QueueOutput" => new MessagePattern(FactTypes.MessageBindingDeclared, RuleIds.MessageSurfaceBinding, EvidenceTiers.Tier2Structural, "azure-functions", "queue-output-attribute", "bind", "bind", "message-queue", 0),
            "ServiceBusOutput" => new MessagePattern(FactTypes.MessageBindingDeclared, RuleIds.MessageSurfaceBinding, EvidenceTiers.Tier2Structural, "azure-functions", "servicebus-output-attribute", "bind", "bind", "message-topic", 0),
            "Topic" => new MessagePattern(FactTypes.MessageBindingDeclared, RuleIds.MessageSurfaceBinding, EvidenceTiers.Tier2Structural, "dapr", "topic-attribute", "bind", "bind", "message-topic", 1),
            _ => null
        };
    }

    private static bool IsInProcessMediatorInvocation(string invocationName, string? receiverName, InvocationExpressionSyntax invocation)
    {
        if (invocationName is not ("Publish" or "PublishAsync" or "Send" or "SendAsync"))
        {
            return false;
        }

        var receiver = receiverName ?? string.Empty;
        return receiver.Contains("mediator", StringComparison.OrdinalIgnoreCase)
            || invocation.Expression.ToString().Contains("MediatR", StringComparison.OrdinalIgnoreCase);
    }

    private static bool LooksLikeExternalMessageReceiver(string? receiverName)
    {
        if (string.IsNullOrWhiteSpace(receiverName))
        {
            return false;
        }

        return receiverName.Contains("bus", StringComparison.OrdinalIgnoreCase)
            || receiverName.Contains("queue", StringComparison.OrdinalIgnoreCase)
            || receiverName.Contains("topic", StringComparison.OrdinalIgnoreCase)
            || receiverName.Contains("kafka", StringComparison.OrdinalIgnoreCase)
            || receiverName.Contains("producer", StringComparison.OrdinalIgnoreCase)
            || receiverName.Contains("consumer", StringComparison.OrdinalIgnoreCase)
            || receiverName.Contains("dapr", StringComparison.OrdinalIgnoreCase)
            || receiverName.Contains("rabbit", StringComparison.OrdinalIgnoreCase)
            || receiverName.Contains("channel", StringComparison.OrdinalIgnoreCase)
            || receiverName.Contains("endpoint", StringComparison.OrdinalIgnoreCase);
    }

    private static string FrameworkFromReceiver(string? receiverName)
    {
        var receiver = receiverName ?? string.Empty;
        if (receiver.Contains("kafka", StringComparison.OrdinalIgnoreCase) || receiver.Contains("producer", StringComparison.OrdinalIgnoreCase) || receiver.Contains("consumer", StringComparison.OrdinalIgnoreCase))
        {
            return "kafka";
        }

        if (receiver.Contains("dapr", StringComparison.OrdinalIgnoreCase))
        {
            return "dapr";
        }

        if (receiver.Contains("rabbit", StringComparison.OrdinalIgnoreCase) || receiver.Contains("channel", StringComparison.OrdinalIgnoreCase))
        {
            return "rabbitmq";
        }

        if (receiver.Contains("bus", StringComparison.OrdinalIgnoreCase) || receiver.Contains("endpoint", StringComparison.OrdinalIgnoreCase))
        {
            return "message-bus";
        }

        return "message-framework";
    }

    private static IReadOnlyDictionary<string, string?> ExtractStringConstants(CompilationUnitSyntax root)
    {
        var constants = new SortedDictionary<string, string?>(StringComparer.Ordinal);
        foreach (var declaration in root.DescendantNodes().OfType<VariableDeclaratorSyntax>())
        {
            var fieldOrLocal = declaration.Parent?.Parent;
            var isConst = fieldOrLocal switch
            {
                FieldDeclarationSyntax field => field.Modifiers.Any(SyntaxKind.ConstKeyword),
                LocalDeclarationStatementSyntax local => local.Modifiers.Any(SyntaxKind.ConstKeyword),
                _ => false
            };
            if (!isConst || declaration.Initializer?.Value is not LiteralExpressionSyntax literal || !IsStringLiteralToken(literal.Token))
            {
                continue;
            }

            var name = declaration.Identifier.ValueText;
            AddConstant(constants, name, literal.Token.ValueText);

            if (fieldOrLocal is FieldDeclarationSyntax)
            {
                var typePath = string.Join(
                    ".",
                    declaration.Ancestors()
                        .OfType<TypeDeclarationSyntax>()
                        .Reverse()
                        .Select(type => type.Identifier.ValueText));
                if (!string.IsNullOrWhiteSpace(typePath))
                {
                    AddConstant(constants, $"{typePath}.{name}", literal.Token.ValueText);
                }
            }
        }

        return constants;
    }

    private static void AddConstant(SortedDictionary<string, string?> constants, string name, string value)
    {
        if (constants.TryGetValue(name, out var existing))
        {
            constants[name] = existing == value ? existing : null;
        }
        else
        {
            constants[name] = value;
        }
    }

    private static bool TryGetStaticString(SeparatedSyntaxList<ArgumentSyntax> arguments, int index, IReadOnlyDictionary<string, string?> constants, out string value)
    {
        value = string.Empty;
        if (arguments.Count <= index)
        {
            return false;
        }

        return TryGetStaticString(arguments[index].Expression, constants, out value);
    }

    private static bool TryGetStaticString(SeparatedSyntaxList<AttributeArgumentSyntax> arguments, int index, IReadOnlyDictionary<string, string?> constants, out string value)
    {
        value = string.Empty;
        if (arguments.Count <= index)
        {
            return false;
        }

        return TryGetStaticString(arguments[index].Expression, constants, out value);
    }

    private static bool TryGetStaticString(ExpressionSyntax expression, IReadOnlyDictionary<string, string?> constants, out string value)
    {
        value = string.Empty;
        if (expression is LiteralExpressionSyntax literal && IsStringLiteralToken(literal.Token))
        {
            value = literal.Token.ValueText;
            return true;
        }

        if (expression is IdentifierNameSyntax identifier && constants.TryGetValue(identifier.Identifier.ValueText, out var constantValue) && constantValue is not null)
        {
            value = constantValue;
            return true;
        }

        if (expression is MemberAccessExpressionSyntax memberAccess && constants.TryGetValue(memberAccess.WithoutTrivia().ToString(), out var memberConstantValue) && memberConstantValue is not null)
        {
            value = memberConstantValue;
            return true;
        }

        return false;
    }

    private static bool TryGetLiteralArgument(InvocationExpressionSyntax invocation, int index, out string value)
    {
        value = string.Empty;
        var arguments = invocation.ArgumentList.Arguments;
        if (arguments.Count <= index)
        {
            return false;
        }

        if (arguments[index].Expression is LiteralExpressionSyntax literal
            && IsStringLiteralToken(literal.Token)
            && literal.Token.ValueText is { Length: >= 0 } literalValue)
        {
            value = literalValue;
            return true;
        }

        return false;
    }

    private static bool IsStaticStringLiteral(ExpressionSyntax expression)
    {
        return expression is LiteralExpressionSyntax literal && IsStringLiteralToken(literal.Token);
    }

    private static string GetSqlSourceKind(SyntaxNode? node)
    {
        var invocation = node?.AncestorsAndSelf().OfType<InvocationExpressionSyntax>().FirstOrDefault();
        if (invocation is not null && EfRawSqlMethods.Contains(GetInvocationName(invocation.Expression)))
        {
            return "orm-text";
        }

        return "literal-string";
    }

    private static string ContainingSymbol(string filePath, string? containingType, string? containingMethod)
    {
        return containingMethod ?? containingType ?? FileInventory.NormalizeRelativePath(filePath);
    }

    private static string? GetContainingMemberName(SyntaxNode? node)
    {
        foreach (var ancestor in node?.AncestorsAndSelf() ?? [])
        {
            switch (ancestor)
            {
                case MethodDeclarationSyntax method:
                    return method.Identifier.ValueText;
                case ConstructorDeclarationSyntax constructor:
                    return constructor.Identifier.ValueText;
                case PropertyDeclarationSyntax property:
                    return property.Identifier.ValueText;
                case AccessorDeclarationSyntax accessor
                    when accessor.Parent?.Parent is PropertyDeclarationSyntax property:
                    return property.Identifier.ValueText;
            }
        }

        return null;
    }

    private static string? GetContainingType(SyntaxNode? node)
    {
        return node?.AncestorsAndSelf()
            .OfType<TypeDeclarationSyntax>()
            .FirstOrDefault()
            ?.Identifier
            .ValueText;
    }

    private static bool IsStringLiteralToken(SyntaxToken token)
    {
        return token.IsKind(SyntaxKind.StringLiteralToken)
            || token.IsKind(SyntaxKind.SingleLineRawStringLiteralToken)
            || token.IsKind(SyntaxKind.MultiLineRawStringLiteralToken)
            || token.IsKind(SyntaxKind.Utf8StringLiteralToken)
            || token.IsKind(SyntaxKind.Utf8SingleLineRawStringLiteralToken)
            || token.IsKind(SyntaxKind.Utf8MultiLineRawStringLiteralToken);
    }

    private static bool IsDbContextTypeName(string typeName)
    {
        return typeName.Equals("DbContext", StringComparison.Ordinal)
            || typeName.EndsWith(".DbContext", StringComparison.Ordinal)
            || typeName.EndsWith("EntityFrameworkCore.DbContext", StringComparison.Ordinal);
    }

    private static bool IsDbSetTypeName(string typeName)
    {
        return typeName.Equals("DbSet", StringComparison.Ordinal)
            || typeName.StartsWith("DbSet<", StringComparison.Ordinal)
            || typeName.EndsWith(".DbSet", StringComparison.Ordinal)
            || typeName.Contains(".DbSet<", StringComparison.Ordinal);
    }

    private static bool IsSqlCommandTypeName(string typeName)
    {
        return typeName.Equals("SqlCommand", StringComparison.Ordinal)
            || typeName.EndsWith(".SqlCommand", StringComparison.Ordinal);
    }

    private static EvidenceSpan ToEvidenceSpan(string filePath, SyntaxNode node)
    {
        var span = node.SyntaxTree.GetLineSpan(node.Span);
        return new EvidenceSpan(
            FileInventory.NormalizeRelativePath(filePath),
            span.StartLinePosition.Line + 1,
            Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
            null,
            "CSharpIntegrationSyntaxExtractor",
            ScannerVersions.CSharpIntegrationSyntaxExtractor);
    }

    private static EvidenceSpan ToEvidenceSpan(string filePath, SyntaxToken token)
    {
        var span = token.SyntaxTree!.GetLineSpan(token.Span);
        return new EvidenceSpan(
            FileInventory.NormalizeRelativePath(filePath),
            span.StartLinePosition.Line + 1,
            Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
            null,
            "CSharpIntegrationSyntaxExtractor",
            ScannerVersions.CSharpIntegrationSyntaxExtractor);
    }

    private static bool IsGeneratedSource(string fullPath)
    {
        var fileName = Path.GetFileName(fullPath);
        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasAutoGeneratedHeader(string source)
    {
        var prefix = source.Length <= 512 ? source : source[..512];
        return prefix.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
            || prefix.Contains("This code was generated", StringComparison.OrdinalIgnoreCase);
    }

    private sealed record MessagePattern(
        string FactType,
        string RuleId,
        string EvidenceTier,
        string FrameworkFamily,
        string FrameworkFeature,
        string OperationDirection,
        string OperationKind,
        string SurfaceKind,
        int DestinationArgumentIndex);
}
