using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.VisualBasic;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;

namespace TraceMap.Core;

// Bounded per-file Visual Basic syntax fallback (spec task 6). Runs only over
// inventoried Visual Basic files that did not receive compiler-resolved
// semantic coverage, emits Tier3SyntaxOrTextual facts under vb.syntax.* rules
// with text names only (never compiler-resolved targets, never symbol-ID
// joins), one Tier4 gap per fallback file, bounded deterministic parse
// diagnostics, and a deterministic per-file fact budget.
public static class VisualBasicSyntaxExtractor
{
    private const int MaxFactsPerFile = 2000;
    private const int MaxParseDiagnosticGapsPerFile = 20;

    public static IReadOnlyList<CodeFact> Extract(
        string repoPath,
        ScanManifest manifest,
        IEnumerable<FileInventoryItem> inventory,
        IReadOnlySet<string>? semanticallyAnalyzedFiles,
        IReadOnlyList<ProtectedSourceSpan>? protectedSourceSpans = null)
    {
        var facts = new List<CodeFact>();
        foreach (var file in inventory
            .Where(item => FileInventory.IsVisualBasicKind(item.Kind))
            .OrderBy(item => item.RelativePath, StringComparer.Ordinal))
        {
            if (semanticallyAnalyzedFiles is not null
                && semanticallyAnalyzedFiles.Contains(file.RelativePath))
            {
                // The compiler-resolved pass already covered this file; adding
                // Tier3 duplicates would only blur evidence strength.
                continue;
            }

            var fullPath = Path.Combine(repoPath, file.RelativePath);
            if (IsGeneratedSource(file.RelativePath))
            {
                continue;
            }

            string source;
            try
            {
                source = File.ReadAllText(fullPath);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.AnalysisGap,
                    RuleIds.VisualBasicSyntaxDeclarations,
                    EvidenceTiers.Tier4Unknown,
                    new EvidenceSpan(file.RelativePath, 1, 1, null, "VisualBasicSyntaxExtractor", ScannerVersions.VisualBasicSyntaxExtractor),
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["gapKind"] = "SyntaxFileReadFailed",
                        ["message"] = "Unable to read the Visual Basic file for syntax fallback; per-file syntax evidence is unavailable.",
                        ["messageHash"] = FactFactory.Hash(ex.GetType().Name, 32),
                        ["sanitization"] = "category-only"
                    }));
                continue;
            }

            if (HasAutoGeneratedHeader(source))
            {
                continue;
            }

            var tree = VisualBasicSyntaxTree.ParseText(SourceText.From(source), path: file.RelativePath);
            AddParseDiagnostics(manifest, facts, tree, file.RelativePath);
            var root = tree.GetCompilationUnitRoot();
            var fileProtectedSpans = protectedSourceSpans?
                .Where(span => span.FilePath.Equals(file.RelativePath, StringComparison.Ordinal))
                .ToArray() ?? [];
            var budget = new FactBudget(MaxFactsPerFile);
            facts.Add(CreateSemanticUnavailableGap(manifest, file.RelativePath));
            AddDeclarationFacts(manifest, facts, file.RelativePath, root, budget);
            AddMemberAccessFacts(manifest, facts, file.RelativePath, root, fileProtectedSpans, budget);
            AddInvocationFacts(manifest, facts, file.RelativePath, root, fileProtectedSpans, budget);
            AddObjectCreationFacts(manifest, facts, file.RelativePath, root, fileProtectedSpans, budget);
        }

        return facts;
    }

    private static void AddDeclarationFacts(
        ScanManifest manifest,
        List<CodeFact> facts,
        string filePath,
        CompilationUnitSyntax root,
        FactBudget budget)
    {
        foreach (var statement in root.DescendantNodes().OfType<TypeStatementSyntax>())
        {
            var declared = statement switch
            {
                ClassStatementSyntax classStatement => (name: classStatement.Identifier.ValueText, kind: "class"),
                ModuleStatementSyntax moduleStatement => (name: moduleStatement.Identifier.ValueText, kind: "module"),
                StructureStatementSyntax structureStatement => (name: structureStatement.Identifier.ValueText, kind: "structure"),
                InterfaceStatementSyntax interfaceStatement => (name: interfaceStatement.Identifier.ValueText, kind: "interface"),
                _ => (name: string.Empty, kind: string.Empty)
            };
            if (declared.name.Length == 0)
            {
                continue;
            }

            var namespaceName = GetSyntacticNamespace(statement);
            var containingTypeNames = statement.Ancestors()
                .OfType<TypeBlockSyntax>()
                .Select(block => block.BlockStatement.Identifier.ValueText)
                .Reverse();
            var qualifiedName = string.Join(".", new[] { namespaceName }
                .Concat(containingTypeNames)
                .Append(declared.name)
                .Where(item => !string.IsNullOrWhiteSpace(item)));
            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.TypeDeclared,
                    RuleIds.VisualBasicSyntaxDeclarations,
                    filePath,
                    statement,
                    targetSymbol: declared.name,
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["kind"] = declared.kind,
                        ["name"] = declared.name,
                        ["namespace"] = namespaceName,
                        ["qualifiedName"] = qualifiedName
                    },
                    budget))
            {
                return;
            }
        }

        foreach (var statement in root.DescendantNodes().OfType<EnumStatementSyntax>())
        {
            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.EnumDeclared,
                    RuleIds.VisualBasicSyntaxDeclarations,
                    filePath,
                    statement,
                    targetSymbol: statement.Identifier.ValueText,
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["kind"] = "enum",
                        ["name"] = statement.Identifier.ValueText
                    },
                    budget))
            {
                return;
            }
        }

        foreach (var statement in root.DescendantNodes().OfType<DelegateStatementSyntax>())
        {
            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.TypeDeclared,
                    RuleIds.VisualBasicSyntaxDeclarations,
                    filePath,
                    statement,
                    targetSymbol: statement.Identifier.ValueText,
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["kind"] = "delegate",
                        ["name"] = statement.Identifier.ValueText
                    },
                    budget))
            {
                return;
            }
        }

        foreach (var statement in root.DescendantNodes().OfType<MethodBaseSyntax>())
        {
            if (statement is DeclareStatementSyntax or AccessorStatementSyntax)
            {
                continue;
            }

            var methodName = statement switch
            {
                MethodStatementSyntax methodStatement => methodStatement.Identifier.ValueText,
                SubNewStatementSyntax => "New",
                OperatorStatementSyntax operatorStatement => operatorStatement.OperatorToken.ValueText,
                _ => string.Empty
            };
            if (methodName.Length == 0)
            {
                continue;
            }

            var containingType = statement.Ancestors()
                .OfType<TypeBlockSyntax>()
                .FirstOrDefault()?.BlockStatement.Identifier.ValueText ?? string.Empty;
            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.MethodDeclared,
                    RuleIds.VisualBasicSyntaxDeclarations,
                    filePath,
                    statement,
                    targetSymbol: methodName,
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["containingType"] = containingType,
                        ["name"] = methodName
                    },
                    budget))
            {
                return;
            }
        }

        foreach (var statement in root.DescendantNodes().OfType<PropertyStatementSyntax>())
        {
            var propertyName = statement.Identifier.ValueText;
            var containingType = statement.Ancestors()
                .OfType<TypeBlockSyntax>()
                .FirstOrDefault()?.BlockStatement.Identifier.ValueText ?? string.Empty;
            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.PropertyDeclared,
                    RuleIds.VisualBasicSyntaxDeclarations,
                    filePath,
                    statement,
                    targetSymbol: string.IsNullOrWhiteSpace(containingType) ? propertyName : $"{containingType}.{propertyName}",
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["containingType"] = containingType,
                        ["name"] = propertyName,
                        ["propertyName"] = propertyName
                    },
                    budget,
                    sourceSymbol: containingType))
            {
                return;
            }
        }
    }

    private static void AddMemberAccessFacts(
        ScanManifest manifest,
        List<CodeFact> facts,
        string filePath,
        CompilationUnitSyntax root,
        IReadOnlyList<ProtectedSourceSpan> protectedSpans,
        FactBudget budget)
    {
        foreach (var memberAccess in root.DescendantNodes().OfType<MemberAccessExpressionSyntax>())
        {
            if (OverlapsProtected(memberAccess, protectedSpans))
            {
                continue;
            }

            var memberName = memberAccess.Name.Identifier.ValueText;
            if (string.IsNullOrWhiteSpace(memberName))
            {
                memberName = memberAccess.Name.ToString();
            }

            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.MemberAccessName,
                    RuleIds.VisualBasicSyntaxMemberAccess,
                    filePath,
                    memberAccess,
                    targetSymbol: memberName,
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["expressionHash"] = FactFactory.Hash(memberAccess.Expression.ToString(), 32),
                        ["expressionKind"] = memberAccess.Expression.Kind().ToString(),
                        ["memberName"] = memberName
                    },
                    budget,
                    sourceSymbol: GetSafeExpressionName(memberAccess.Expression)))
            {
                return;
            }
        }
    }

    private static void AddInvocationFacts(
        ScanManifest manifest,
        List<CodeFact> facts,
        string filePath,
        CompilationUnitSyntax root,
        IReadOnlyList<ProtectedSourceSpan> protectedSpans,
        FactBudget budget)
    {
        foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            if (OverlapsProtected(invocation, protectedSpans))
            {
                continue;
            }

            var invocationName = GetInvocationName(invocation.Expression);
            var containingMember = GetContainingMemberName(invocation);
            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.InvocationName,
                    RuleIds.VisualBasicSyntaxInvocation,
                    filePath,
                    invocation,
                    targetSymbol: invocationName,
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["expressionHash"] = FactFactory.Hash(invocation.Expression.ToString(), 32),
                        ["expressionKind"] = invocation.Expression.Kind().ToString(),
                        ["invocationName"] = invocationName,
                        ["receiverName"] = GetInvocationReceiverName(invocation.Expression) ?? string.Empty
                    },
                    budget))
            {
                return;
            }

            // The callee is invocation text only: never a compiler-resolved
            // target and never a symbol-ID join.
            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.CallEdge,
                    RuleIds.VisualBasicSyntaxCallGraph,
                    filePath,
                    invocation,
                    targetSymbol: invocationName,
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["callKind"] = "SyntaxInvocation",
                        ["calleeName"] = invocationName,
                        ["callerName"] = containingMember ?? string.Empty
                    },
                    budget,
                    sourceSymbol: containingMember))
            {
                return;
            }
        }
    }

    private static void AddObjectCreationFacts(
        ScanManifest manifest,
        List<CodeFact> facts,
        string filePath,
        CompilationUnitSyntax root,
        IReadOnlyList<ProtectedSourceSpan> protectedSpans,
        FactBudget budget)
    {
        foreach (var creation in root.DescendantNodes().OfType<ObjectCreationExpressionSyntax>())
        {
            if (OverlapsProtected(creation, protectedSpans))
            {
                continue;
            }

            var typeName = creation.Type.ToString();
            var containingMember = GetContainingMemberName(creation);
            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.ObjectCreated,
                    RuleIds.VisualBasicSyntaxObjectCreation,
                    filePath,
                    creation,
                    targetSymbol: typeName,
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["argumentCount"] = (creation.ArgumentList?.Arguments.Count ?? 0).ToString(),
                        ["assignedTo"] = GetAssignedVariableName(creation) ?? string.Empty,
                        ["callerName"] = containingMember ?? string.Empty,
                        ["createdType"] = typeName,
                        ["creationKind"] = "SyntaxObjectCreation"
                    },
                    budget,
                    sourceSymbol: containingMember))
            {
                return;
            }

            if (!TryAddSyntaxFact(
                    manifest,
                    facts,
                    FactTypes.CallEdge,
                    RuleIds.VisualBasicSyntaxCallGraph,
                    filePath,
                    creation,
                    targetSymbol: typeName,
                    new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["assignedTo"] = GetAssignedVariableName(creation) ?? string.Empty,
                        ["callKind"] = "SyntaxObjectCreation",
                        ["calleeContainingType"] = typeName,
                        ["calleeName"] = typeName,
                        ["callerName"] = containingMember ?? string.Empty
                    },
                    budget,
                    sourceSymbol: containingMember))
            {
                return;
            }
        }
    }

    private static bool TryAddSyntaxFact(
        ScanManifest manifest,
        List<CodeFact> facts,
        string factType,
        string ruleId,
        string filePath,
        SyntaxNode node,
        string targetSymbol,
        SortedDictionary<string, string> properties,
        FactBudget budget,
        string? sourceSymbol = null)
    {
        if (!budget.TryReserve())
        {
            if (!budget.TruncationReported)
            {
                budget.TruncationReported = true;
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.AnalysisGap,
                    RuleIds.VisualBasicSyntaxDeclarations,
                    EvidenceTiers.Tier4Unknown,
                    new EvidenceSpan(filePath, 1, 1, null, "VisualBasicSyntaxExtractor", ScannerVersions.VisualBasicSyntaxExtractor),
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["budget"] = budget.MaxFacts.ToString(),
                        ["gapKind"] = "SyntaxFallbackBudgetExhausted",
                        ["message"] = $"Visual Basic syntax fallback for this file stopped after {budget.MaxFacts} facts; remaining syntax candidates were not emitted.",
                        ["sanitization"] = "category-only"
                    }));
            }

            return false;
        }

        var span = node.SyntaxTree.GetLineSpan(node.Span);
        facts.Add(FactFactory.Create(
            manifest,
            factType,
            ruleId,
            EvidenceTiers.Tier3SyntaxOrTextual,
            new EvidenceSpan(
                FileInventory.NormalizeRelativePath(filePath),
                span.StartLinePosition.Line + 1,
                Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
                null,
                "VisualBasicSyntaxExtractor",
                ScannerVersions.VisualBasicSyntaxExtractor),
            sourceSymbol: sourceSymbol,
            targetSymbol: targetSymbol,
            properties: properties));
        return true;
    }

    private static CodeFact CreateSemanticUnavailableGap(ScanManifest manifest, string filePath)
    {
        return FactFactory.Create(
            manifest,
            FactTypes.AnalysisGap,
            RuleIds.VisualBasicSemanticWorkspace,
            EvidenceTiers.Tier4Unknown,
            new EvidenceSpan(filePath, 1, 1, null, "VisualBasicSyntaxExtractor", ScannerVersions.VisualBasicSyntaxExtractor),
            properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
            {
                ["coverageEffect"] = "reduces-semantic-coverage",
                ["gapKind"] = "SemanticAnalysisUnavailable",
                ["message"] = "Compiler-resolved Visual Basic analysis was unavailable for this file; only syntax-or-textual evidence was emitted for it.",
                ["sanitization"] = "category-only"
            });
    }

    private static void AddParseDiagnostics(
        ScanManifest manifest,
        List<CodeFact> facts,
        SyntaxTree tree,
        string filePath)
    {
        foreach (var diagnostic in tree.GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .OrderBy(diagnostic => diagnostic.Location.GetLineSpan().StartLinePosition.Line)
            .ThenBy(diagnostic => diagnostic.Id, StringComparer.Ordinal)
            .Take(MaxParseDiagnosticGapsPerFile))
        {
            var span = diagnostic.Location.GetLineSpan();
            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.AnalysisGap,
                RuleIds.VisualBasicSyntaxDeclarations,
                EvidenceTiers.Tier4Unknown,
                new EvidenceSpan(
                    FileInventory.NormalizeRelativePath(filePath),
                    span.StartLinePosition.Line + 1,
                    Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
                    null,
                    "VisualBasicSyntaxExtractor",
                    ScannerVersions.VisualBasicSyntaxExtractor),
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    // The raw compiler message text is deliberately omitted; the
                    // bounded diagnostic code and message hash stay deterministic
                    // without retaining source-derived text.
                    ["diagnosticId"] = diagnostic.Id,
                    ["gapKind"] = "SyntaxParseDiagnostic",
                    ["messageHash"] = FactFactory.Hash(diagnostic.GetMessage(), 32)
                }));
        }
    }

    private static string GetSyntacticNamespace(SyntaxNode declaration)
    {
        return string.Join(".", declaration.Ancestors()
            .OfType<NamespaceBlockSyntax>()
            .Select(block => block.NamespaceStatement.Name.ToString())
            .Reverse()
            .Where(item => !string.IsNullOrWhiteSpace(item)));
    }

    private static string GetInvocationName(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => memberAccess.Name.Identifier.ValueText,
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            _ => expression.ToString()
        };
    }

    private static string? GetInvocationReceiverName(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => GetSafeExpressionName(memberAccess.Expression),
            _ => null
        };
    }

    private static string? GetSafeExpressionName(ExpressionSyntax expression)
    {
        return expression switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            MeExpressionSyntax => "Me",
            MyBaseExpressionSyntax => "MyBase",
            MemberAccessExpressionSyntax memberAccess
                when GetSafeExpressionName(memberAccess.Expression) is { Length: > 0 } receiver =>
                $"{receiver}.{memberAccess.Name.Identifier.ValueText}",
            InvocationExpressionSyntax invocation => GetInvocationName(invocation.Expression),
            _ => null
        };
    }

    private static string? GetContainingMemberName(SyntaxNode node)
    {
        foreach (var ancestor in node.Ancestors())
        {
            switch (ancestor)
            {
                case MethodBlockSyntax methodBlock:
                    return QualifyContainingMember(methodBlock, methodBlock.SubOrFunctionStatement.Identifier.ValueText, methodBlock.SubOrFunctionStatement.ParameterList?.Parameters.Count ?? 0);
                case ConstructorBlockSyntax constructorBlock:
                    return QualifyContainingMember(constructorBlock, "New", constructorBlock.SubNewStatement.ParameterList?.Parameters.Count ?? 0);
                case OperatorBlockSyntax operatorBlock:
                    return QualifyContainingMember(operatorBlock, operatorBlock.OperatorStatement.OperatorToken.ValueText, operatorBlock.OperatorStatement.ParameterList?.Parameters.Count ?? 0);
                case PropertyBlockSyntax propertyBlock:
                    return QualifyContainingMember(propertyBlock, propertyBlock.PropertyStatement.Identifier.ValueText, 0);
            }
        }

        return null;
    }

    private static string QualifyContainingMember(SyntaxNode member, string memberName, int parameterCount)
    {
        var typeNames = member
            .Ancestors()
            .OfType<TypeBlockSyntax>()
            .Select(type => type.BlockStatement.Identifier.ValueText)
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Reverse()
            .ToArray();
        var typePrefix = typeNames.Length == 0 ? "global" : string.Join(".", typeNames);
        return $"{typePrefix}.{memberName}/{parameterCount}";
    }

    private static string? GetAssignedVariableName(ObjectCreationExpressionSyntax creation)
    {
        if (creation.Parent is AsNewClauseSyntax { Parent: VariableDeclaratorSyntax declarator })
        {
            return declarator.Names.FirstOrDefault()?.Identifier.ValueText;
        }

        if (creation.Parent is AssignmentStatementSyntax assignment)
        {
            return GetSafeExpressionName(assignment.Left);
        }

        return null;
    }

    private static bool OverlapsProtected(SyntaxNode node, IReadOnlyList<ProtectedSourceSpan> protectedSpans)
    {
        foreach (var span in protectedSpans)
        {
            if (node.SpanStart < span.Start + span.Length && span.Start < node.Span.End)
            {
                return true;
            }
        }

        return false;
    }

    private static bool HasAutoGeneratedHeader(string source)
    {
        var prefixLength = Math.Min(source.Length, 512);
        return source[..prefixLength].Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
            || source[..prefixLength].Contains("<autogenerated", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsGeneratedSource(string relativePath)
    {
        var fileName = Path.GetFileName(relativePath);
        return fileName.EndsWith(".g.vb", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.vb", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.vb", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.vb", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".AssemblyInfo.vb", StringComparison.OrdinalIgnoreCase);
    }

    private sealed class FactBudget(int maxFacts)
    {
        public int MaxFacts { get; } = maxFacts;
        public bool TruncationReported { get; set; }
        private int Remaining { get; set; } = maxFacts;

        public bool TryReserve()
        {
            if (Remaining <= 0)
            {
                return false;
            }

            Remaining--;
            return true;
        }
    }
}
