<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace></RootNamespace>
    <AssemblyName>PublicLazy.Framework</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../messy-dotnet-workspace/vb-lazy-logging-provider/PublicLog.vb" />
    <Reference Include="System.Data" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>
