class EvidenceTiers:
    TIER1 = "Tier1Semantic"
    TIER2 = "Tier2Structural"
    TIER3 = "Tier3SyntaxOrTextual"
    TIER4 = "Tier4Unknown"


class FactTypes:
    REPO_SCANNED = "RepoScanned"
    BUILD_STATUS = "BuildStatus"
    ANALYSIS_GAP = "AnalysisGap"
    FILE_INVENTORIED = "FileInventoried"
    PACKAGE_REFERENCED = "PackageReferenced"
    CONFIG_FILE_DECLARED = "ConfigFileDeclared"
    SQL_FILE_DECLARED = "SqlFileDeclared"
    TYPE_DECLARED = "TypeDeclared"
    METHOD_DECLARED = "MethodDeclared"
    FIELD_DECLARED = "FieldDeclared"
    PARAMETER_DECLARED = "ParameterDeclared"
    MEMBER_ACCESS_NAME = "MemberAccessName"
    INVOCATION_NAME = "InvocationName"
    CALL_EDGE = "CallEdge"
    OBJECT_CREATED = "ObjectCreated"
    ARGUMENT_PASSED = "ArgumentPassed"
    LOCAL_ALIAS = "LocalAlias"
    FIELD_ALIAS = "FieldAlias"
    SYMBOL_RELATIONSHIP = "SymbolRelationship"
    HTTP_ROUTE_BINDING = "HttpRouteBinding"
    HTTP_CALL_DETECTED = "HttpCallDetected"
    DATABASE_COLUMN_MAPPING = "DatabaseColumnMapping"
    SERIALIZER_CONTRACT_MEMBER = "SerializerContractMember"
    SQL_TEXT_USED = "SqlTextUsed"
    QUERY_PATTERN_DETECTED = "QueryPatternDetected"
    CONFIG_KEY_DECLARED = "ConfigKeyDeclared"
    INFRASTRUCTURE_BOILERPLATE = "InfrastructureBoilerplate"


class RuleIds:
    REPO_MANIFEST = "repo.manifest.v1"
    FILE_INVENTORY = "file.inventory.v1"
    PY_PACKAGE = "python.package.metadata.v1"
    PY_DECLARATIONS = "python.ast.declarations.v1"
    PY_IMPORTS = "python.ast.imports.v1"
    PY_INVOCATION = "python.ast.invocation.v1"
    PY_CALLGRAPH = "python.ast.callgraph.v1"
    PY_OBJECT = "python.ast.objectcreation.v1"
    PY_ARGUMENT = "python.ast.argumentflow.v1"
    PY_RELATIONSHIP = "python.ast.relationships.v1"
    PY_BOUNDARY = "python.ast.dynamic-boundary.v1"
    FASTAPI = "python.integration.fastapi.v1"
    FLASK = "python.integration.flask.v1"
    PYDANTIC = "python.integration.pydantic.v1"
    DATACLASS = "python.integration.dataclass.v1"
    SQLALCHEMY = "python.integration.sqlalchemy.v1"
    SQL = "python.integration.sql.v1"
    CONFIG = "python.integration.config.v1"
    HTTP_CLIENT = "python.integration.httpclient.v1"
    BOILERPLATE = "python.boilerplate.v1"


class ScannerVersions:
    TRACE_MAP_PY = "python-adapter/0.1.0"
    REPO = "python-repo/0.1.0"
    INVENTORY = "python-inventory/0.1.0"
    METADATA = "python-metadata/0.1.0"
    CONFIG = "python-config/0.1.0"
    AST = "python-ast/0.1.0"
    INTEGRATION = "python-integration/0.1.0"
    SQL = "python-sql/0.1.0"
