using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TraceMap.Core;

public static class CSharpSyntaxExtractor
{
    public static IReadOnlyList<CodeFact> Extract(string repoPath, ScanManifest manifest, IEnumerable<FileInventoryItem> inventory)
    {
        var facts = new List<CodeFact>();
        foreach (var file in inventory
            .Where(item => item.Kind == "CSharp")
            .OrderBy(item => item.RelativePath, StringComparer.Ordinal))
        {
            var fullPath = Path.Combine(repoPath, file.RelativePath);
            if (TryGetBoilerplateCategory(file.RelativePath, out var boilerplateCategory))
            {
                facts.Add(CreateFileShapeFact(manifest, file.RelativePath, FactTypes.InfrastructureBoilerplate, boilerplateCategory));
            }

            if (IsGeneratedSource(fullPath))
            {
                continue;
            }

            try
            {
                var source = File.ReadAllText(fullPath);
                if (HasAutoGeneratedHeader(source))
                {
                    continue;
                }

                var tree = CSharpSyntaxTree.ParseText(SourceText.From(source), path: file.RelativePath);
                var root = tree.GetCompilationUnitRoot();
                AddParseDiagnostics(manifest, facts, tree);
                AddDeclarationFacts(manifest, facts, file.RelativePath, root);
                AddAttributeFacts(manifest, facts, file.RelativePath, root);
                AddMemberAccessFacts(manifest, facts, file.RelativePath, root);
                AddInvocationFacts(manifest, facts, file.RelativePath, root);
                AddLogicShapeFacts(manifest, facts, file.RelativePath, root);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                facts.Add(FactFactory.Create(
                    manifest,
                    FactTypes.AnalysisGap,
                    RuleIds.CSharpSyntaxDeclarations,
                    EvidenceTiers.Tier4Unknown,
                    new EvidenceSpan(file.RelativePath, 1, 1, null, "CSharpSyntaxExtractor", ScannerVersions.CSharpSyntaxExtractor),
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["message"] = $"Unable to read C# file for syntax extraction: {ex.Message}"
                    }));
            }
        }

        return facts;
    }

    private static void AddDeclarationFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var node in root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>())
        {
            switch (node)
            {
                case EnumDeclarationSyntax enumDeclaration:
                    facts.Add(CreateSyntaxFact(
                        manifest,
                        FactTypes.EnumDeclared,
                        RuleIds.CSharpSyntaxDeclarations,
                        filePath,
                        enumDeclaration,
                        targetSymbol: enumDeclaration.Identifier.ValueText,
                        properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                        {
                            ["name"] = enumDeclaration.Identifier.ValueText,
                            ["kind"] = "enum"
                        }));
                    break;
                case TypeDeclarationSyntax typeDeclaration:
                    facts.Add(CreateSyntaxFact(
                        manifest,
                        FactTypes.TypeDeclared,
                        RuleIds.CSharpSyntaxDeclarations,
                        filePath,
                        typeDeclaration,
                        targetSymbol: typeDeclaration.Identifier.ValueText,
                        properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                        {
                            ["name"] = typeDeclaration.Identifier.ValueText,
                            ["kind"] = typeDeclaration.Keyword.ValueText
                        }));
                    break;
            }
        }

        foreach (var method in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
        {
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.MethodDeclared,
                RuleIds.CSharpSyntaxDeclarations,
                filePath,
                method,
                targetSymbol: method.Identifier.ValueText,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["name"] = method.Identifier.ValueText
                }));
        }

        foreach (var property in root.DescendantNodes().OfType<PropertyDeclarationSyntax>())
        {
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.PropertyDeclared,
                RuleIds.CSharpSyntaxDeclarations,
                filePath,
                property,
                targetSymbol: property.Identifier.ValueText,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["name"] = property.Identifier.ValueText
                }));
        }
    }

    private static void AddAttributeFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var attribute in root.DescendantNodes().OfType<AttributeSyntax>())
        {
            var attributeName = attribute.Name.ToString();
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.AttributeUsed,
                RuleIds.CSharpSyntaxDeclarations,
                filePath,
                attribute,
                targetSymbol: attributeName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["name"] = attributeName
                }));
        }
    }

    private static void AddMemberAccessFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var memberAccess in root.DescendantNodes().OfType<MemberAccessExpressionSyntax>())
        {
            var memberName = memberAccess.Name.Identifier.ValueText;
            if (string.IsNullOrWhiteSpace(memberName))
            {
                memberName = memberAccess.Name.ToString();
            }

            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.MemberAccessName,
                RuleIds.CSharpSyntaxMemberAccess,
                filePath,
                memberAccess,
                sourceSymbol: memberAccess.Expression.ToString(),
                targetSymbol: memberName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["expression"] = memberAccess.Expression.ToString(),
                    ["memberName"] = memberName
                }));
        }
    }

    private static void AddInvocationFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            var invocationName = GetInvocationName(invocation.Expression);
            var containingMember = GetContainingMemberName(invocation);
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.InvocationName,
                RuleIds.CSharpSyntaxInvocation,
                filePath,
                invocation,
                targetSymbol: invocationName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["expression"] = invocation.Expression.ToString(),
                    ["invocationName"] = invocationName
                }));

            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.CallEdge,
                RuleIds.CSharpSyntaxCallGraph,
                filePath,
                invocation,
                sourceSymbol: containingMember,
                targetSymbol: invocationName,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["callerName"] = containingMember ?? string.Empty,
                    ["calleeName"] = invocationName,
                    ["callKind"] = "SyntaxInvocation"
                }));

            if (IsSerializationName(invocationName) || invocation.Expression.ToString().Contains("Serializer", StringComparison.Ordinal))
            {
                facts.Add(CreateSyntaxFact(
                    manifest,
                    FactTypes.SerializationLogic,
                    RuleIds.CSharpSyntaxLogicShape,
                    filePath,
                    invocation,
                    sourceSymbol: containingMember,
                    targetSymbol: invocationName,
                    properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                    {
                        ["callerName"] = containingMember ?? string.Empty,
                        ["operationName"] = invocationName
                    }));
            }
        }
    }

    private static void AddLogicShapeFacts(ScanManifest manifest, List<CodeFact> facts, string filePath, CompilationUnitSyntax root)
    {
        foreach (var binary in root.DescendantNodes().OfType<BinaryExpressionSyntax>().Where(IsCalculationExpression))
        {
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.CalculationExpression,
                RuleIds.CSharpSyntaxLogicShape,
                filePath,
                binary,
                sourceSymbol: GetContainingMemberName(binary),
                targetSymbol: "calculation",
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["containingMember"] = GetContainingMemberName(binary) ?? string.Empty,
                    ["operator"] = binary.OperatorToken.ValueText,
                    ["expressionHash"] = FactFactory.Hash(binary.ToString(), 32)
                }));
        }

        foreach (var branch in root.DescendantNodes().Where(IsBranchingNode))
        {
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.BranchingLogic,
                RuleIds.CSharpSyntaxLogicShape,
                filePath,
                branch,
                sourceSymbol: GetContainingMemberName(branch),
                targetSymbol: branch.Kind().ToString(),
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["branchKind"] = branch.Kind().ToString(),
                    ["containingMember"] = GetContainingMemberName(branch) ?? string.Empty
                }));
        }

        foreach (var method in root.DescendantNodes().OfType<MethodDeclarationSyntax>().Where(method => LooksLikeRetryPolicyLogic(filePath, method)))
        {
            facts.Add(CreateSyntaxFact(
                manifest,
                FactTypes.RetryPolicyLogic,
                RuleIds.CSharpSyntaxLogicShape,
                filePath,
                method,
                sourceSymbol: method.Identifier.ValueText,
                targetSymbol: method.Identifier.ValueText,
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["methodName"] = method.Identifier.ValueText,
                    ["className"] = method.Ancestors().OfType<TypeDeclarationSyntax>().FirstOrDefault()?.Identifier.ValueText ?? string.Empty,
                    ["matchedBy"] = "RetryBackoffNamingOrTimeSpan"
                }));
        }
    }

    private static string GetInvocationName(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => string.IsNullOrWhiteSpace(memberAccess.Name.Identifier.ValueText)
                ? memberAccess.Name.ToString()
                : memberAccess.Name.Identifier.ValueText,
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax genericName => genericName.Identifier.ValueText,
            MemberBindingExpressionSyntax memberBinding => memberBinding.Name.Identifier.ValueText,
            _ => expression.ToString()
        };
    }

    private static string? GetContainingMemberName(SyntaxNode node)
    {
        if (node.Ancestors().OfType<MethodDeclarationSyntax>().FirstOrDefault() is { } method)
        {
            return method.Identifier.ValueText;
        }

        if (node.Ancestors().OfType<ConstructorDeclarationSyntax>().FirstOrDefault() is { } constructor)
        {
            return constructor.Identifier.ValueText;
        }

        if (node.Ancestors().OfType<PropertyDeclarationSyntax>().FirstOrDefault() is { } property)
        {
            return property.Identifier.ValueText;
        }

        return null;
    }

    private static bool IsCalculationExpression(BinaryExpressionSyntax binary)
    {
        return binary.IsKind(SyntaxKind.MultiplyExpression)
            || binary.IsKind(SyntaxKind.DivideExpression)
            || binary.IsKind(SyntaxKind.ModuloExpression)
            || HasCalculationCall(binary)
            || HasNumericLiteral(binary);
    }

    private static bool HasCalculationCall(SyntaxNode node)
    {
        return node.DescendantNodesAndSelf()
            .OfType<MemberAccessExpressionSyntax>()
            .Any(memberAccess => memberAccess.Expression.ToString().Equals("Math", StringComparison.Ordinal)
                || memberAccess.Expression.ToString().Equals("TimeSpan", StringComparison.Ordinal));
    }

    private static bool HasNumericLiteral(SyntaxNode node)
    {
        return node.DescendantNodesAndSelf()
            .OfType<LiteralExpressionSyntax>()
            .Any(literal => literal.IsKind(SyntaxKind.NumericLiteralExpression));
    }

    private static bool IsBranchingNode(SyntaxNode node)
    {
        return node is IfStatementSyntax
            or SwitchStatementSyntax
            or ConditionalExpressionSyntax
            or ForStatementSyntax
            or ForEachStatementSyntax
            or WhileStatementSyntax
            or DoStatementSyntax;
    }

    private static bool LooksLikeRetryPolicyLogic(string filePath, MethodDeclarationSyntax method)
    {
        var className = method.Ancestors().OfType<TypeDeclarationSyntax>().FirstOrDefault()?.Identifier.ValueText ?? string.Empty;
        var signatureText = $"{filePath} {className} {method.Identifier.ValueText}";
        return signatureText.Contains("Retry", StringComparison.OrdinalIgnoreCase)
            || signatureText.Contains("Backoff", StringComparison.OrdinalIgnoreCase)
            || method.Identifier.ValueText.Equals("GetShouldRetry", StringComparison.Ordinal)
            || method.DescendantNodes().OfType<MemberAccessExpressionSyntax>().Any(memberAccess => memberAccess.Expression.ToString().Equals("TimeSpan", StringComparison.Ordinal));
    }

    private static bool IsSerializationName(string name)
    {
        return name.Contains("Serialize", StringComparison.OrdinalIgnoreCase)
            || name.Contains("Deserialize", StringComparison.OrdinalIgnoreCase);
    }

    private static void AddParseDiagnostics(ScanManifest manifest, List<CodeFact> facts, SyntaxTree tree)
    {
        foreach (var diagnostic in tree.GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .OrderBy(diagnostic => diagnostic.Location.GetLineSpan().StartLinePosition.Line)
            .ThenBy(diagnostic => diagnostic.Id, StringComparer.Ordinal))
        {
            var span = diagnostic.Location.GetLineSpan();
            var filePath = FileInventory.NormalizeRelativePath(span.Path);
            facts.Add(FactFactory.Create(
                manifest,
                FactTypes.AnalysisGap,
                RuleIds.CSharpSyntaxDeclarations,
                EvidenceTiers.Tier4Unknown,
                new EvidenceSpan(
                    filePath,
                    span.StartLinePosition.Line + 1,
                    Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
                    null,
                    "CSharpSyntaxExtractor",
                    ScannerVersions.CSharpSyntaxExtractor),
                properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
                {
                    ["diagnosticId"] = diagnostic.Id,
                    ["message"] = diagnostic.GetMessage()
                }));
        }
    }

    private static CodeFact CreateSyntaxFact(
        ScanManifest manifest,
        string factType,
        string ruleId,
        string filePath,
        SyntaxNode node,
        string? sourceSymbol = null,
        string? targetSymbol = null,
        IReadOnlyDictionary<string, string>? properties = null)
    {
        return FactFactory.Create(
            manifest,
            factType,
            ruleId,
            EvidenceTiers.Tier3SyntaxOrTextual,
            ToEvidenceSpan(filePath, node),
            sourceSymbol: sourceSymbol,
            targetSymbol: targetSymbol,
            contractElement: factType == FactTypes.CallEdge ? targetSymbol : null,
            properties: properties);
    }

    private static CodeFact CreateFileShapeFact(ScanManifest manifest, string filePath, string factType, string category)
    {
        return FactFactory.Create(
            manifest,
            factType,
            RuleIds.CSharpSyntaxLogicShape,
            EvidenceTiers.Tier2Structural,
            new EvidenceSpan(filePath, 1, 1, null, "CSharpSyntaxExtractor", ScannerVersions.CSharpSyntaxExtractor),
            targetSymbol: category,
            properties: new SortedDictionary<string, string>(StringComparer.Ordinal)
            {
                ["category"] = category,
                ["path"] = filePath
            });
    }

    private static EvidenceSpan ToEvidenceSpan(string filePath, SyntaxNode node)
    {
        var span = node.SyntaxTree.GetLineSpan(node.Span);
        return new EvidenceSpan(
            filePath,
            span.StartLinePosition.Line + 1,
            Math.Max(span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1),
            null,
            "CSharpSyntaxExtractor",
            ScannerVersions.CSharpSyntaxExtractor);
    }

    private static bool IsGeneratedSource(string fullPath)
    {
        var fileName = Path.GetFileName(fullPath);
        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool TryGetBoilerplateCategory(string relativePath, out string category)
    {
        var fileName = Path.GetFileName(relativePath);
        if (fileName.Equals("AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase))
        {
            category = "AssemblyMetadata";
            return true;
        }

        if (fileName.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase))
        {
            category = "GeneratedSource";
            return true;
        }

        if (relativePath.Contains("/obj/", StringComparison.OrdinalIgnoreCase)
            || relativePath.Contains("\\obj\\", StringComparison.OrdinalIgnoreCase))
        {
            category = "BuildOutput";
            return true;
        }

        if (relativePath.Contains("/Container/", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith("BuilderExtensions.cs", StringComparison.OrdinalIgnoreCase))
        {
            category = "DependencyInjectionGlue";
            return true;
        }

        category = string.Empty;
        return false;
    }

    private static bool HasAutoGeneratedHeader(string source)
    {
        var prefix = source.Length <= 512 ? source : source[..512];
        return prefix.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
            || prefix.Contains("This code was generated", StringComparison.OrdinalIgnoreCase);
    }
}
