# No configuration needed: reuses the index and Forms block in the existing runner.
param([string[]]$ReportPaths = @())
$ErrorActionPreference = 'Stop'
if ($ReportPaths.Count -eq 0) {
    & (Join-Path $PSScriptRoot 'Run-FocusedWebFormsPageList.ps1') -CompareDepths
    return
}
if ($ReportPaths.Count -ne 3) { throw 'Expected the depth 8, 10, and 12 reports in that order.' }

$packets = @($ReportPaths | ForEach-Object { Get-Content -LiteralPath $_ -Raw | ConvertFrom-Json })
# Compare exact retained source and selection metadata before comparing counts.
$baselineSources = $packets[0].sources | ConvertTo-Json -Depth 20 -Compress
$baselineSelection = $packets[0].surfaceSelection.items | ConvertTo-Json -Depth 20 -Compress
foreach ($packet in $packets) {
    if (($packet.sources | ConvertTo-Json -Depth 20 -Compress) -cne $baselineSources -or
        ($packet.surfaceSelection.items | ConvertTo-Json -Depth 20 -Compress) -cne $baselineSelection) {
        throw 'Source provenance or selected pages differ; the reports are not comparable.'
    }
}

Write-Host 'focused-webforms-depth-comparison=completed'
Write-Host 'countScope=retained-static-evidence-only'
Write-Host 'distinctTerminalBasis=boundaryKind+boundaryTargetId+terminalEvidenceId;not-distinct-runtime-operations'
$previous = @{}
$overview = [Collections.Generic.List[string]]::new()
for ($i = 0; $i -lt 3; $i++) {
    $depth = @(8, 10, 12)[$i]
    $packet = $packets[$i]
    $boundaries = @($packet.downstreamBoundaries)
    $keys = @{}
    foreach ($boundary in $boundaries) {
        if ([string]::IsNullOrWhiteSpace($boundary.boundaryTargetId) -or
            [string]::IsNullOrWhiteSpace($boundary.terminalEvidenceId)) {
            throw 'Boundary identity is incomplete; cannot count distinct retained terminals.'
        }
        $key = @($boundary.boundaryKind, $boundary.boundaryTargetId, $boundary.terminalEvidenceId) | ConvertTo-Json -Compress
        $keys[$key] = $true
    }
    $added = @($keys.Keys | Where-Object { -not $previous.ContainsKey($_) }).Count
    $lost = @($previous.Keys | Where-Object { -not $keys.ContainsKey($_) }).Count
    $terminalPages = @($boundaries.surfaceId | Sort-Object -Unique).Count
    $overview.Add("depth=$depth|truncated=$([bool]$packet.summary.truncated)|chains=$(@($packet.eventChains).Count)|boundaryRecords=$($boundaries.Count)|distinctTerminals=$($keys.Count)|pagesWithTerminal=$terminalPages")
    if ($i -gt 0) { $overview.Add("depthDelta=$depth|addedTerminalIdentities=$added|lostTerminalIdentities=$lost") }
    foreach ($item in @($packet.surfaceSelection.items)) {
        # Never print paths or inferred names; aliases are generated by page-list selection.
        $alias = if ($item.alias -cmatch '^page-[0-9]+$') { $item.alias } else { 'alias-unavailable' }
        $pageKeys = @{}
        foreach ($boundary in $boundaries) {
            if ($boundary.surfaceId -in @($item.surfaceIds)) {
                $key = @($boundary.boundaryKind, $boundary.boundaryTargetId, $boundary.terminalEvidenceId) | ConvertTo-Json -Compress
                $pageKeys[$key] = $true
            }
        }
        Write-Host "depthPage=$depth|alias=$alias|distinctTerminals=$($pageKeys.Count)"
    }
    foreach ($reason in @('cycle', 'depth', 'frontier', 'path', 'unavailable')) {
        $count = @($packet.gaps | Where-Object {
            $_.classification -eq 'TruncatedByLimit' -and
            $(if ($_.truncationReason -cin @('cycle', 'depth', 'frontier', 'path')) { $_.truncationReason } else { 'unavailable' }) -eq $reason
        }).Count
        $overview.Add("depthGap=$depth|reason=$reason|count=$count")
    }
    $otherLimits = @($packet.gaps | Where-Object { $_.classification -match 'LimitReached' }).Count
    $overview.Add("depthOtherLimits=$depth|count=$otherLimits")
    $previous = $keys
}
Write-Host 'depth-comparison-overview'
foreach ($line in $overview) { Write-Host $line }
Write-Host 'nonClaim=more-depth-may-change-bounded-subsets;zero-does-not-prove-absence;no-runtime-execution-or-successful-binding-claim'
