// <auto-generated />
namespace Generated.Pages;

// The generated method bridges to a hand-written terminal. TraceMap must not
// silently treat a source traversal through this excluded body as complete.
public static class GeneratedBridge
{
    public static void Run() => Generated.Data.Terminal.Query();
}
